// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Persona.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Persona.OpenApiClient.UserAuditLogs.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \user-audit-logs\{user-audit-log-id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UserAuditLogItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Persona.OpenApiClient.UserAuditLogs.Item.UserAuditLogItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UserAuditLogItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/user-audit-logs/{user%2Daudit%2Dlog%2Did}{?fields*,include*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Persona.OpenApiClient.UserAuditLogs.Item.UserAuditLogItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UserAuditLogItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/user-audit-logs/{user%2Daudit%2Dlog%2Did}{?fields*,include*}", rawUrl)
        {
        }
        /// <summary>
        /// &quot;Retrieves the details of an existing user audit logs for up to the most recent 6 months.Note: You must use a production API key to access this endpoint. For security reasons, we do not expose organization-level resources like user audit logs in Sandbox via API.&quot;
        /// Full documentation for this API on the Persona website. <see href="https://docs.withpersona.com/api-reference/user-audit-logs/retrieve-an-user-audit-log" />
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Persona.OpenApiClient.Models.Retrieve_a_user_audit_log_200"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Persona.OpenApiClient.Models.Retrieve_a_user_audit_log_200400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Persona.OpenApiClient.Models.Retrieve_a_user_audit_log_200401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Persona.OpenApiClient.Models.Retrieve_a_user_audit_log_200403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Persona.OpenApiClient.Models.Retrieve_a_user_audit_log_200404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Persona.OpenApiClient.Models.Retrieve_a_user_audit_log_200429Error">When receiving a 429 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Persona.OpenApiClient.Models.Retrieve_a_user_audit_log_200?> GetAsync(Action<RequestConfiguration<global::Soenneker.Persona.OpenApiClient.UserAuditLogs.Item.UserAuditLogItemRequestBuilder.UserAuditLogItemRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Persona.OpenApiClient.Models.Retrieve_a_user_audit_log_200> GetAsync(Action<RequestConfiguration<global::Soenneker.Persona.OpenApiClient.UserAuditLogs.Item.UserAuditLogItemRequestBuilder.UserAuditLogItemRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Persona.OpenApiClient.Models.Retrieve_a_user_audit_log_200400Error.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Persona.OpenApiClient.Models.Retrieve_a_user_audit_log_200401Error.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Persona.OpenApiClient.Models.Retrieve_a_user_audit_log_200403Error.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Persona.OpenApiClient.Models.Retrieve_a_user_audit_log_200404Error.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Persona.OpenApiClient.Models.Retrieve_a_user_audit_log_200429Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Persona.OpenApiClient.Models.Retrieve_a_user_audit_log_200>(requestInfo, global::Soenneker.Persona.OpenApiClient.Models.Retrieve_a_user_audit_log_200.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// &quot;Retrieves the details of an existing user audit logs for up to the most recent 6 months.Note: You must use a production API key to access this endpoint. For security reasons, we do not expose organization-level resources like user audit logs in Sandbox via API.&quot;
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Persona.OpenApiClient.UserAuditLogs.Item.UserAuditLogItemRequestBuilder.UserAuditLogItemRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Persona.OpenApiClient.UserAuditLogs.Item.UserAuditLogItemRequestBuilder.UserAuditLogItemRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Persona.OpenApiClient.UserAuditLogs.Item.UserAuditLogItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Persona.OpenApiClient.UserAuditLogs.Item.UserAuditLogItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Persona.OpenApiClient.UserAuditLogs.Item.UserAuditLogItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// &quot;Retrieves the details of an existing user audit logs for up to the most recent 6 months.Note: You must use a production API key to access this endpoint. For security reasons, we do not expose organization-level resources like user audit logs in Sandbox via API.&quot;
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class UserAuditLogItemRequestBuilderGetQueryParameters 
        {
            /// <summary>Comma-separated list(s) of attributes to include in the response. This can be used to customize which attributes will be serialized in the response. See [Serialization](https://docs.withpersona.com/serialization#sparse-fieldsets) for more details.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("fields")]
            public string? Fields { get; set; }
#nullable restore
#else
            [QueryParameter("fields")]
            public string Fields { get; set; }
#endif
            /// <summary>A comma-separated list of relationship paths. This can be used to customize which related resources will be fully serialized in the `included` key in the response. See [Serialization](https://docs.withpersona.com/serialization#inclusion-of-related-resources) for more details.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("include")]
            public string? Include { get; set; }
#nullable restore
#else
            [QueryParameter("include")]
            public string Include { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
