// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Persona.OpenApiClient.Cases.Item;
using Soenneker.Persona.OpenApiClient.Cases.Search;
using Soenneker.Persona.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Persona.OpenApiClient.Cases
{
    /// <summary>
    /// Builds and executes requests for operations under \cases
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CasesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The search property</summary>
        public global::Soenneker.Persona.OpenApiClient.Cases.Search.SearchRequestBuilder Search
        {
            get => new global::Soenneker.Persona.OpenApiClient.Cases.Search.SearchRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Soenneker.Persona.OpenApiClient.cases.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Soenneker.Persona.OpenApiClient.Cases.Item.CaseItemRequestBuilder"/></returns>
        public global::Soenneker.Persona.OpenApiClient.Cases.Item.CaseItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("case%2Did", position);
                return new global::Soenneker.Persona.OpenApiClient.Cases.Item.CaseItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Persona.OpenApiClient.Cases.CasesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CasesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/cases{?fields*,filter*,include*,page*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Persona.OpenApiClient.Cases.CasesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CasesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/cases{?fields*,filter*,include*,page*}", rawUrl)
        {
        }
        /// <summary>
        /// Returns a list of your organization&apos;s cases.Note that this endpoint aggregates cases across all case template(s). See [Pagination](https://docs.withpersona.com/pagination)for more details about handling the response. Results are returned in reverse chronological order, with the most recently created objects first.
        /// Full documentation for this API on the Persona website. <see href="https://docs.withpersona.com/api-reference/cases/list-all-cases" />
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Persona.OpenApiClient.Models.ListAllCases200"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Persona.OpenApiClient.Models.ListAllCases200400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Persona.OpenApiClient.Models.ListAllCases200401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Persona.OpenApiClient.Models.ListAllCases200403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Persona.OpenApiClient.Models.ListAllCases200404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Persona.OpenApiClient.Models.ListAllCases200429Error">When receiving a 429 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Persona.OpenApiClient.Models.ListAllCases200?> GetAsync(Action<RequestConfiguration<global::Soenneker.Persona.OpenApiClient.Cases.CasesRequestBuilder.CasesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Persona.OpenApiClient.Models.ListAllCases200> GetAsync(Action<RequestConfiguration<global::Soenneker.Persona.OpenApiClient.Cases.CasesRequestBuilder.CasesRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Persona.OpenApiClient.Models.ListAllCases200400Error.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Persona.OpenApiClient.Models.ListAllCases200401Error.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Persona.OpenApiClient.Models.ListAllCases200403Error.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Persona.OpenApiClient.Models.ListAllCases200404Error.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Persona.OpenApiClient.Models.ListAllCases200429Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Persona.OpenApiClient.Models.ListAllCases200>(requestInfo, global::Soenneker.Persona.OpenApiClient.Models.ListAllCases200.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Creates a new case in your organization.
        /// Full documentation for this API on the Persona website. <see href="https://docs.withpersona.com/api-reference/cases/create-a-case" />
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Persona.OpenApiClient.Models.CreateACase201"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Persona.OpenApiClient.Models.CreateACase201400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Persona.OpenApiClient.Models.CreateACase201401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Persona.OpenApiClient.Models.CreateACase201403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Persona.OpenApiClient.Models.CreateACase201404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Persona.OpenApiClient.Models.CreateACase201409Error">When receiving a 409 status code</exception>
        /// <exception cref="global::Soenneker.Persona.OpenApiClient.Models.CreateACase201422Error">When receiving a 422 status code</exception>
        /// <exception cref="global::Soenneker.Persona.OpenApiClient.Models.CreateACase201429Error">When receiving a 429 status code</exception>
        /// <exception cref="global::Soenneker.Persona.OpenApiClient.Models.CreateACase201503Error">When receiving a 503 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Persona.OpenApiClient.Models.CreateACase201?> PostAsync(global::Soenneker.Persona.OpenApiClient.Models.CreateACase body, Action<RequestConfiguration<global::Soenneker.Persona.OpenApiClient.Cases.CasesRequestBuilder.CasesRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Persona.OpenApiClient.Models.CreateACase201> PostAsync(global::Soenneker.Persona.OpenApiClient.Models.CreateACase body, Action<RequestConfiguration<global::Soenneker.Persona.OpenApiClient.Cases.CasesRequestBuilder.CasesRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Persona.OpenApiClient.Models.CreateACase201400Error.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Persona.OpenApiClient.Models.CreateACase201401Error.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Persona.OpenApiClient.Models.CreateACase201403Error.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Persona.OpenApiClient.Models.CreateACase201404Error.CreateFromDiscriminatorValue },
                { "409", global::Soenneker.Persona.OpenApiClient.Models.CreateACase201409Error.CreateFromDiscriminatorValue },
                { "422", global::Soenneker.Persona.OpenApiClient.Models.CreateACase201422Error.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Persona.OpenApiClient.Models.CreateACase201429Error.CreateFromDiscriminatorValue },
                { "503", global::Soenneker.Persona.OpenApiClient.Models.CreateACase201503Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Persona.OpenApiClient.Models.CreateACase201>(requestInfo, global::Soenneker.Persona.OpenApiClient.Models.CreateACase201.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns a list of your organization&apos;s cases.Note that this endpoint aggregates cases across all case template(s). See [Pagination](https://docs.withpersona.com/pagination)for more details about handling the response. Results are returned in reverse chronological order, with the most recently created objects first.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Persona.OpenApiClient.Cases.CasesRequestBuilder.CasesRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Persona.OpenApiClient.Cases.CasesRequestBuilder.CasesRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Creates a new case in your organization.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Persona.OpenApiClient.Models.CreateACase body, Action<RequestConfiguration<global::Soenneker.Persona.OpenApiClient.Cases.CasesRequestBuilder.CasesRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Persona.OpenApiClient.Models.CreateACase body, Action<RequestConfiguration<global::Soenneker.Persona.OpenApiClient.Cases.CasesRequestBuilder.CasesRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Persona.OpenApiClient.Cases.CasesRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Persona.OpenApiClient.Cases.CasesRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Persona.OpenApiClient.Cases.CasesRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Returns a list of your organization&apos;s cases.Note that this endpoint aggregates cases across all case template(s). See [Pagination](https://docs.withpersona.com/pagination)for more details about handling the response. Results are returned in reverse chronological order, with the most recently created objects first.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CasesRequestBuilderGetQueryParameters 
        {
            /// <summary>Comma-separated list(s) of attributes to include in the response. This can be used to customize which attributes will be serialized in the response. See [Serialization](https://docs.withpersona.com/serialization#sparse-fieldsets) for more details.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("fields")]
            public string? Fields { get; set; }
#nullable restore
#else
            [QueryParameter("fields")]
            public string Fields { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("filter")]
            public string? Filter { get; set; }
#nullable restore
#else
            [QueryParameter("filter")]
            public string Filter { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("page")]
            public string? Page { get; set; }
#nullable restore
#else
            [QueryParameter("page")]
            public string Page { get; set; }
#endif
        }
        /// <summary>
        /// Creates a new case in your organization.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CasesRequestBuilderPostQueryParameters 
        {
            /// <summary>Comma-separated list(s) of attributes to include in the response. This can be used to customize which attributes will be serialized in the response. See [Serialization](https://docs.withpersona.com/serialization#sparse-fieldsets) for more details.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("fields")]
            public string? Fields { get; set; }
#nullable restore
#else
            [QueryParameter("fields")]
            public string Fields { get; set; }
#endif
            /// <summary>A comma-separated list of relationship paths. This can be used to customize which related resources will be fully serialized in the `included` key in the response. See [Serialization](https://docs.withpersona.com/serialization#inclusion-of-related-resources) for more details.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("include")]
            public string? Include { get; set; }
#nullable restore
#else
            [QueryParameter("include")]
            public string Include { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
