// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Persona.OpenApiClient.ListItem.BrowserFingerprints;
using Soenneker.Persona.OpenApiClient.ListItem.Countries;
using Soenneker.Persona.OpenApiClient.ListItem.DeviceFingerprints;
using Soenneker.Persona.OpenApiClient.ListItem.EmailAddresses;
using Soenneker.Persona.OpenApiClient.ListItem.Fields;
using Soenneker.Persona.OpenApiClient.ListItem.Geolocations;
using Soenneker.Persona.OpenApiClient.ListItem.GovernmentIdNumbers;
using Soenneker.Persona.OpenApiClient.ListItem.IpAddresses;
using Soenneker.Persona.OpenApiClient.ListItem.Names;
using Soenneker.Persona.OpenApiClient.ListItem.PhoneNumbers;
using Soenneker.Persona.OpenApiClient.ListItem.Strings;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Persona.OpenApiClient.ListItem
{
    /// <summary>
    /// Builds and executes requests for operations under \list-item
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ListItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The browserFingerprints property</summary>
        public global::Soenneker.Persona.OpenApiClient.ListItem.BrowserFingerprints.BrowserFingerprintsRequestBuilder BrowserFingerprints
        {
            get => new global::Soenneker.Persona.OpenApiClient.ListItem.BrowserFingerprints.BrowserFingerprintsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The countries property</summary>
        public global::Soenneker.Persona.OpenApiClient.ListItem.Countries.CountriesRequestBuilder Countries
        {
            get => new global::Soenneker.Persona.OpenApiClient.ListItem.Countries.CountriesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The deviceFingerprints property</summary>
        public global::Soenneker.Persona.OpenApiClient.ListItem.DeviceFingerprints.DeviceFingerprintsRequestBuilder DeviceFingerprints
        {
            get => new global::Soenneker.Persona.OpenApiClient.ListItem.DeviceFingerprints.DeviceFingerprintsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The emailAddresses property</summary>
        public global::Soenneker.Persona.OpenApiClient.ListItem.EmailAddresses.EmailAddressesRequestBuilder EmailAddresses
        {
            get => new global::Soenneker.Persona.OpenApiClient.ListItem.EmailAddresses.EmailAddressesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The fields property</summary>
        public global::Soenneker.Persona.OpenApiClient.ListItem.Fields.FieldsRequestBuilder Fields
        {
            get => new global::Soenneker.Persona.OpenApiClient.ListItem.Fields.FieldsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The geolocations property</summary>
        public global::Soenneker.Persona.OpenApiClient.ListItem.Geolocations.GeolocationsRequestBuilder Geolocations
        {
            get => new global::Soenneker.Persona.OpenApiClient.ListItem.Geolocations.GeolocationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The governmentIdNumbers property</summary>
        public global::Soenneker.Persona.OpenApiClient.ListItem.GovernmentIdNumbers.GovernmentIdNumbersRequestBuilder GovernmentIdNumbers
        {
            get => new global::Soenneker.Persona.OpenApiClient.ListItem.GovernmentIdNumbers.GovernmentIdNumbersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The ipAddresses property</summary>
        public global::Soenneker.Persona.OpenApiClient.ListItem.IpAddresses.IpAddressesRequestBuilder IpAddresses
        {
            get => new global::Soenneker.Persona.OpenApiClient.ListItem.IpAddresses.IpAddressesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The names property</summary>
        public global::Soenneker.Persona.OpenApiClient.ListItem.Names.NamesRequestBuilder Names
        {
            get => new global::Soenneker.Persona.OpenApiClient.ListItem.Names.NamesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The phoneNumbers property</summary>
        public global::Soenneker.Persona.OpenApiClient.ListItem.PhoneNumbers.PhoneNumbersRequestBuilder PhoneNumbers
        {
            get => new global::Soenneker.Persona.OpenApiClient.ListItem.PhoneNumbers.PhoneNumbersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The strings property</summary>
        public global::Soenneker.Persona.OpenApiClient.ListItem.Strings.StringsRequestBuilder Strings
        {
            get => new global::Soenneker.Persona.OpenApiClient.ListItem.Strings.StringsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Persona.OpenApiClient.ListItem.ListItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ListItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/list-item", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Persona.OpenApiClient.ListItem.ListItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ListItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/list-item", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
