// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Persona.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Persona.OpenApiClient.ListItem.BrowserFingerprints.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \list-item\browser-fingerprints\{list-item-id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ListItemItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Persona.OpenApiClient.ListItem.BrowserFingerprints.Item.ListItemItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ListItemItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/list-item/browser-fingerprints/{list%2Ditem%2Did}{?fields*,include*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Persona.OpenApiClient.ListItem.BrowserFingerprints.Item.ListItemItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ListItemItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/list-item/browser-fingerprints/{list%2Ditem%2Did}{?fields*,include*}", rawUrl)
        {
        }
        /// <summary>
        /// Archived items are not matched against new inquiries.
        /// Full documentation for this API on the Persona website. <see href="https://docs.withpersona.com/api-reference/list-items/archive-a-browser-fingerprint-list-item" />
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Persona.OpenApiClient.ListItem.BrowserFingerprints.Item.ListItemDeleteResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Persona.OpenApiClient.Models.ListItem400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Persona.OpenApiClient.Models.ListItem401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Persona.OpenApiClient.Models.ListItem403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Persona.OpenApiClient.Models.ListItem404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Persona.OpenApiClient.Models.ListItem409Error">When receiving a 409 status code</exception>
        /// <exception cref="global::Soenneker.Persona.OpenApiClient.Models.ListItem422Error">When receiving a 422 status code</exception>
        /// <exception cref="global::Soenneker.Persona.OpenApiClient.Models.ListItem429Error">When receiving a 429 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Persona.OpenApiClient.ListItem.BrowserFingerprints.Item.ListItemDeleteResponse?> DeleteAsync(Action<RequestConfiguration<global::Soenneker.Persona.OpenApiClient.ListItem.BrowserFingerprints.Item.ListItemItemRequestBuilder.ListItemItemRequestBuilderDeleteQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Persona.OpenApiClient.ListItem.BrowserFingerprints.Item.ListItemDeleteResponse> DeleteAsync(Action<RequestConfiguration<global::Soenneker.Persona.OpenApiClient.ListItem.BrowserFingerprints.Item.ListItemItemRequestBuilder.ListItemItemRequestBuilderDeleteQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Persona.OpenApiClient.Models.ListItem400Error.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Persona.OpenApiClient.Models.ListItem401Error.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Persona.OpenApiClient.Models.ListItem403Error.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Persona.OpenApiClient.Models.ListItem404Error.CreateFromDiscriminatorValue },
                { "409", global::Soenneker.Persona.OpenApiClient.Models.ListItem409Error.CreateFromDiscriminatorValue },
                { "422", global::Soenneker.Persona.OpenApiClient.Models.ListItem422Error.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Persona.OpenApiClient.Models.ListItem429Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Persona.OpenApiClient.ListItem.BrowserFingerprints.Item.ListItemDeleteResponse>(requestInfo, global::Soenneker.Persona.OpenApiClient.ListItem.BrowserFingerprints.Item.ListItemDeleteResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrieves the details of an existing browser fingerprint List Item.
        /// Full documentation for this API on the Persona website. <see href="https://docs.withpersona.com/api-reference/list-items/retrieve-a-browser-fingerprint-list-item" />
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Persona.OpenApiClient.ListItem.BrowserFingerprints.Item.ListItemGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Persona.OpenApiClient.Models.ListItem400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Persona.OpenApiClient.Models.ListItem401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Persona.OpenApiClient.Models.ListItem403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Persona.OpenApiClient.Models.ListItem404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Persona.OpenApiClient.Models.ListItem409Error">When receiving a 409 status code</exception>
        /// <exception cref="global::Soenneker.Persona.OpenApiClient.Models.ListItem422Error">When receiving a 422 status code</exception>
        /// <exception cref="global::Soenneker.Persona.OpenApiClient.Models.ListItem429Error">When receiving a 429 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Persona.OpenApiClient.ListItem.BrowserFingerprints.Item.ListItemGetResponse?> GetAsync(Action<RequestConfiguration<global::Soenneker.Persona.OpenApiClient.ListItem.BrowserFingerprints.Item.ListItemItemRequestBuilder.ListItemItemRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Persona.OpenApiClient.ListItem.BrowserFingerprints.Item.ListItemGetResponse> GetAsync(Action<RequestConfiguration<global::Soenneker.Persona.OpenApiClient.ListItem.BrowserFingerprints.Item.ListItemItemRequestBuilder.ListItemItemRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Persona.OpenApiClient.Models.ListItem400Error.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Persona.OpenApiClient.Models.ListItem401Error.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Persona.OpenApiClient.Models.ListItem403Error.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Persona.OpenApiClient.Models.ListItem404Error.CreateFromDiscriminatorValue },
                { "409", global::Soenneker.Persona.OpenApiClient.Models.ListItem409Error.CreateFromDiscriminatorValue },
                { "422", global::Soenneker.Persona.OpenApiClient.Models.ListItem422Error.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Persona.OpenApiClient.Models.ListItem429Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Persona.OpenApiClient.ListItem.BrowserFingerprints.Item.ListItemGetResponse>(requestInfo, global::Soenneker.Persona.OpenApiClient.ListItem.BrowserFingerprints.Item.ListItemGetResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Archived items are not matched against new inquiries.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<global::Soenneker.Persona.OpenApiClient.ListItem.BrowserFingerprints.Item.ListItemItemRequestBuilder.ListItemItemRequestBuilderDeleteQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<global::Soenneker.Persona.OpenApiClient.ListItem.BrowserFingerprints.Item.ListItemItemRequestBuilder.ListItemItemRequestBuilderDeleteQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Retrieves the details of an existing browser fingerprint List Item.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Persona.OpenApiClient.ListItem.BrowserFingerprints.Item.ListItemItemRequestBuilder.ListItemItemRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Persona.OpenApiClient.ListItem.BrowserFingerprints.Item.ListItemItemRequestBuilder.ListItemItemRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Persona.OpenApiClient.ListItem.BrowserFingerprints.Item.ListItemItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Persona.OpenApiClient.ListItem.BrowserFingerprints.Item.ListItemItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Persona.OpenApiClient.ListItem.BrowserFingerprints.Item.ListItemItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Archived items are not matched against new inquiries.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ListItemItemRequestBuilderDeleteQueryParameters 
        {
            /// <summary>Comma-separated list(s) of attributes to include in the response. This can be used to customize which attributes will be serialized in the response. See [Serialization](https://docs.withpersona.com/serialization#sparse-fieldsets) for more details.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("fields")]
            public string? Fields { get; set; }
#nullable restore
#else
            [QueryParameter("fields")]
            public string Fields { get; set; }
#endif
            /// <summary>A comma-separated list of relationship paths. This can be used to customize which related resources will be fully serialized in the `included` key in the response. See [Serialization](https://docs.withpersona.com/serialization#inclusion-of-related-resources) for more details.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("include")]
            public string? Include { get; set; }
#nullable restore
#else
            [QueryParameter("include")]
            public string Include { get; set; }
#endif
        }
        /// <summary>
        /// Retrieves the details of an existing browser fingerprint List Item.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ListItemItemRequestBuilderGetQueryParameters 
        {
            /// <summary>Comma-separated list(s) of attributes to include in the response. This can be used to customize which attributes will be serialized in the response. See [Serialization](https://docs.withpersona.com/serialization#sparse-fieldsets) for more details.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("fields")]
            public string? Fields { get; set; }
#nullable restore
#else
            [QueryParameter("fields")]
            public string Fields { get; set; }
#endif
            /// <summary>A comma-separated list of relationship paths. This can be used to customize which related resources will be fully serialized in the `included` key in the response. See [Serialization](https://docs.withpersona.com/serialization#inclusion-of-related-resources) for more details.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("include")]
            public string? Include { get; set; }
#nullable restore
#else
            [QueryParameter("include")]
            public string Include { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
