// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Persona.OpenApiClient.Connect.ShareTokens.Item.Expire;
using Soenneker.Persona.OpenApiClient.Connect.ShareTokens.Item.Redeem;
using Soenneker.Persona.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Persona.OpenApiClient.Connect.ShareTokens.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \connect\share-tokens\{shareTokenId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithShareTokenItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The expire property</summary>
        public global::Soenneker.Persona.OpenApiClient.Connect.ShareTokens.Item.Expire.ExpireRequestBuilder Expire
        {
            get => new global::Soenneker.Persona.OpenApiClient.Connect.ShareTokens.Item.Expire.ExpireRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The redeem property</summary>
        public global::Soenneker.Persona.OpenApiClient.Connect.ShareTokens.Item.Redeem.RedeemRequestBuilder Redeem
        {
            get => new global::Soenneker.Persona.OpenApiClient.Connect.ShareTokens.Item.Redeem.RedeemRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Persona.OpenApiClient.Connect.ShareTokens.Item.WithShareTokenItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithShareTokenItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/connect/share-tokens/{shareTokenId}{?fields*,include*,peek%2Dsource%2Ddata*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Persona.OpenApiClient.Connect.ShareTokens.Item.WithShareTokenItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithShareTokenItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/connect/share-tokens/{shareTokenId}{?fields*,include*,peek%2Dsource%2Ddata*}", rawUrl)
        {
        }
        /// <summary>
        /// Retrieve the information for an existing Share Token.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Persona.OpenApiClient.Models.RetrieveAShareToken200Response"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Persona.OpenApiClient.Models.BadRequestResponse">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Persona.OpenApiClient.Models.UnauthorizedResponse">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Persona.OpenApiClient.Models.ForbiddenResponse">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Persona.OpenApiClient.Models.NotFoundResponse">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Persona.OpenApiClient.Models.ConflictResponse">When receiving a 409 status code</exception>
        /// <exception cref="global::Soenneker.Persona.OpenApiClient.Models.TooManyRequestsResponse">When receiving a 429 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Persona.OpenApiClient.Models.RetrieveAShareToken200Response?> GetAsync(Action<RequestConfiguration<global::Soenneker.Persona.OpenApiClient.Connect.ShareTokens.Item.WithShareTokenItemRequestBuilder.WithShareTokenItemRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Persona.OpenApiClient.Models.RetrieveAShareToken200Response> GetAsync(Action<RequestConfiguration<global::Soenneker.Persona.OpenApiClient.Connect.ShareTokens.Item.WithShareTokenItemRequestBuilder.WithShareTokenItemRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Persona.OpenApiClient.Models.BadRequestResponse.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Persona.OpenApiClient.Models.UnauthorizedResponse.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Persona.OpenApiClient.Models.ForbiddenResponse.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Persona.OpenApiClient.Models.NotFoundResponse.CreateFromDiscriminatorValue },
                { "409", global::Soenneker.Persona.OpenApiClient.Models.ConflictResponse.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Persona.OpenApiClient.Models.TooManyRequestsResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Persona.OpenApiClient.Models.RetrieveAShareToken200Response>(requestInfo, global::Soenneker.Persona.OpenApiClient.Models.RetrieveAShareToken200Response.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrieve the information for an existing Share Token.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Persona.OpenApiClient.Connect.ShareTokens.Item.WithShareTokenItemRequestBuilder.WithShareTokenItemRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Persona.OpenApiClient.Connect.ShareTokens.Item.WithShareTokenItemRequestBuilder.WithShareTokenItemRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Persona.OpenApiClient.Connect.ShareTokens.Item.WithShareTokenItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Persona.OpenApiClient.Connect.ShareTokens.Item.WithShareTokenItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Persona.OpenApiClient.Connect.ShareTokens.Item.WithShareTokenItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Retrieve the information for an existing Share Token.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithShareTokenItemRequestBuilderGetQueryParameters 
        {
            /// <summary>Comma-separated list(s) of attributes to include in the response. This can be used to customize which attributes will be serialized in the response. See [Serialization](https://docs.withpersona.com/serialization#sparse-fieldsets) for more details.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("fields")]
            public string? Fields { get; set; }
#nullable restore
#else
            [QueryParameter("fields")]
            public string Fields { get; set; }
#endif
            /// <summary>A comma-separated list of relationship paths. This can be used to customize which related resources will be fully serialized in the `included` key in the response. See [Serialization](https://docs.withpersona.com/serialization#inclusion-of-related-resources) for more details.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("include")]
            public string? Include { get; set; }
#nullable restore
#else
            [QueryParameter("include")]
            public string Include { get; set; }
#endif
            /// <summary>When `true`, the caller is the destination organization, and the destination organizationhas access to the source data peek capability, the response&apos;s`data.attributes.source-data` carries a PII-filtered source-data envelope. Defaults to`false`; omitted from list responses regardless.</summary>
            [QueryParameter("peek%2Dsource%2Ddata")]
            public bool? PeekSourceData { get; set; }
        }
    }
}
#pragma warning restore CS0618
