// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Persona.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AccountTypeRelationships : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The accountStatuses property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Persona.OpenApiClient.Models.AccountTypeRelationshipsAccountStatuses? AccountStatuses { get; set; }
#nullable restore
#else
        public global::Soenneker.Persona.OpenApiClient.Models.AccountTypeRelationshipsAccountStatuses AccountStatuses { get; set; }
#endif
        /// <summary>The defaultAccountStatus property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Persona.OpenApiClient.Models.AccountTypeRelationshipsDefaultAccountStatus? DefaultAccountStatus { get; set; }
#nullable restore
#else
        public global::Soenneker.Persona.OpenApiClient.Models.AccountTypeRelationshipsDefaultAccountStatus DefaultAccountStatus { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Persona.OpenApiClient.Models.AccountTypeRelationships"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Persona.OpenApiClient.Models.AccountTypeRelationships CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Persona.OpenApiClient.Models.AccountTypeRelationships();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "account-statuses", n => { AccountStatuses = n.GetObjectValue<global::Soenneker.Persona.OpenApiClient.Models.AccountTypeRelationshipsAccountStatuses>(global::Soenneker.Persona.OpenApiClient.Models.AccountTypeRelationshipsAccountStatuses.CreateFromDiscriminatorValue); } },
                { "default-account-status", n => { DefaultAccountStatus = n.GetObjectValue<global::Soenneker.Persona.OpenApiClient.Models.AccountTypeRelationshipsDefaultAccountStatus>(global::Soenneker.Persona.OpenApiClient.Models.AccountTypeRelationshipsDefaultAccountStatus.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Persona.OpenApiClient.Models.AccountTypeRelationshipsAccountStatuses>("account-statuses", AccountStatuses);
            writer.WriteObjectValue<global::Soenneker.Persona.OpenApiClient.Models.AccountTypeRelationshipsDefaultAccountStatus>("default-account-status", DefaultAccountStatus);
        }
    }
}
#pragma warning restore CS0618
