// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Persona.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Api_log_attributes : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The createdAt property</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The request property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Persona.OpenApiClient.Models.Api_log_attributes_request? Request { get; set; }
#nullable restore
#else
        public global::Soenneker.Persona.OpenApiClient.Models.Api_log_attributes_request Request { get; set; }
#endif
        /// <summary>The response property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Persona.OpenApiClient.Models.Api_log_attributes_response? Response { get; set; }
#nullable restore
#else
        public global::Soenneker.Persona.OpenApiClient.Models.Api_log_attributes_response Response { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Persona.OpenApiClient.Models.Api_log_attributes"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Persona.OpenApiClient.Models.Api_log_attributes CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Persona.OpenApiClient.Models.Api_log_attributes();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "created-at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "request", n => { Request = n.GetObjectValue<global::Soenneker.Persona.OpenApiClient.Models.Api_log_attributes_request>(global::Soenneker.Persona.OpenApiClient.Models.Api_log_attributes_request.CreateFromDiscriminatorValue); } },
                { "response", n => { Response = n.GetObjectValue<global::Soenneker.Persona.OpenApiClient.Models.Api_log_attributes_response>(global::Soenneker.Persona.OpenApiClient.Models.Api_log_attributes_response.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("created-at", CreatedAt);
            writer.WriteObjectValue<global::Soenneker.Persona.OpenApiClient.Models.Api_log_attributes_request>("request", Request);
            writer.WriteObjectValue<global::Soenneker.Persona.OpenApiClient.Models.Api_log_attributes_response>("response", Response);
        }
    }
}
#pragma warning restore CS0618
