// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Persona.OpenApiClient.Models
{
    /// <summary>
    /// Error counts for a Batch Job, independent of which page of row errors was requested.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class BatchJobErrorsMeta : IParsable
    {
        /// <summary>Total number of rows that failed to process, across the whole run (not just this page).</summary>
        public int? ErrorCount { get; set; }
        /// <summary>Errors that affected the whole run rather than a single row.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Persona.OpenApiClient.Models.BatchJobErrorsMetaGlobalErrorsItem>? GlobalErrors { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Persona.OpenApiClient.Models.BatchJobErrorsMetaGlobalErrorsItem> GlobalErrors { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Persona.OpenApiClient.Models.BatchJobErrorsMeta"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Persona.OpenApiClient.Models.BatchJobErrorsMeta CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Persona.OpenApiClient.Models.BatchJobErrorsMeta();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "error-count", n => { ErrorCount = n.GetIntValue(); } },
                { "global-errors", n => { GlobalErrors = n.GetCollectionOfObjectValues<global::Soenneker.Persona.OpenApiClient.Models.BatchJobErrorsMetaGlobalErrorsItem>(global::Soenneker.Persona.OpenApiClient.Models.BatchJobErrorsMetaGlobalErrorsItem.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("error-count", ErrorCount);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Persona.OpenApiClient.Models.BatchJobErrorsMetaGlobalErrorsItem>("global-errors", GlobalErrors);
        }
    }
}
#pragma warning restore CS0618
