// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Persona.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Cases : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The extractionType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExtractionType { get; set; }
#nullable restore
#else
        public string ExtractionType { get; set; }
#endif
        /// <summary>The fieldName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FieldName { get; set; }
#nullable restore
#else
        public string FieldName { get; set; }
#endif
        /// <summary>A list of objects containing the actual value extracted and additional information relevant to the extraction result.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Persona.OpenApiClient.Models.Cases_results>? Results { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Persona.OpenApiClient.Models.Cases_results> Results { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Persona.OpenApiClient.Models.Cases"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Persona.OpenApiClient.Models.Cases CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Persona.OpenApiClient.Models.Cases();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "extraction-type", n => { ExtractionType = n.GetStringValue(); } },
                { "field-name", n => { FieldName = n.GetStringValue(); } },
                { "results", n => { Results = n.GetCollectionOfObjectValues<global::Soenneker.Persona.OpenApiClient.Models.Cases_results>(global::Soenneker.Persona.OpenApiClient.Models.Cases_results.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("extraction-type", ExtractionType);
            writer.WriteStringValue("field-name", FieldName);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Persona.OpenApiClient.Models.Cases_results>("results", Results);
        }
    }
}
#pragma warning restore CS0618
