// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Persona.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CreateAccessTokenXWwwFormUrlencodedRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>A signed JWT (RS256 or ES256) with claims: iss, sub (both set to the client_id), aud (the token endpoint URL), jti, iat, and exp (max 5 minutes from now).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ClientAssertion { get; set; }
#nullable restore
#else
        public string ClientAssertion { get; set; }
#endif
        /// <summary>Must be &apos;urn:ietf:params:oauth:client-assertion-type:jwt-bearer&apos;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ClientAssertionType { get; set; }
#nullable restore
#else
        public string ClientAssertionType { get; set; }
#endif
        /// <summary>Authorization Code</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Code { get; set; }
#nullable restore
#else
        public string Code { get; set; }
#endif
        /// <summary>Must be set to &apos;client_credentials&apos;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Grant_type { get; set; }
#nullable restore
#else
        public string Grant_type { get; set; }
#endif
        /// <summary>Must be set to &apos;authorization_code&apos;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GrantType { get; set; }
#nullable restore
#else
        public string GrantType { get; set; }
#endif
        /// <summary>Optional space-separated list of permissions to request. Must be a subset of the OAuth client&apos;s registered permissions. Defaults to all client permissions if omitted.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Scope { get; set; }
#nullable restore
#else
        public string Scope { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Persona.OpenApiClient.Models.CreateAccessTokenXWwwFormUrlencodedRequest"/> and sets the default values.
        /// </summary>
        public CreateAccessTokenXWwwFormUrlencodedRequest()
        {
            AdditionalData = new Dictionary<string, object>();
            GrantType = "authorization_code";
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Persona.OpenApiClient.Models.CreateAccessTokenXWwwFormUrlencodedRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Persona.OpenApiClient.Models.CreateAccessTokenXWwwFormUrlencodedRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Persona.OpenApiClient.Models.CreateAccessTokenXWwwFormUrlencodedRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "client_assertion", n => { ClientAssertion = n.GetStringValue(); } },
                { "client_assertion_type", n => { ClientAssertionType = n.GetStringValue(); } },
                { "code", n => { Code = n.GetStringValue(); } },
                { "grant-type", n => { GrantType = n.GetStringValue(); } },
                { "scope", n => { Scope = n.GetStringValue(); } },
                { "grant_type", n => { Grant_type = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("client_assertion", ClientAssertion);
            writer.WriteStringValue("client_assertion_type", ClientAssertionType);
            writer.WriteStringValue("code", Code);
            writer.WriteStringValue("grant_type", Grant_type);
            writer.WriteStringValue("grant-type", GrantType);
            writer.WriteStringValue("scope", Scope);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
