// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Persona.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CreateAnAccount_data_attributes : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Name of the status to set on this Account.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AccountStatus { get; set; }
#nullable restore
#else
        public string AccountStatus { get; set; }
#endif
        /// <summary>Account Type ID to create the account for. Starts with `acttp_`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AccountTypeId { get; set; }
#nullable restore
#else
        public string AccountTypeId { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>City of residence address. Not all international addresses use this attribute.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AddressCity { get; set; }
#nullable restore
#else
        public string AddressCity { get; set; }
#endif
        /// <summary>ZIP or postal code of residence address. Not all international addresses use this attribute.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AddressPostalCode { get; set; }
#nullable restore
#else
        public string AddressPostalCode { get; set; }
#endif
        /// <summary>Street name of residence address.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AddressStreet1 { get; set; }
#nullable restore
#else
        public string AddressStreet1 { get; set; }
#endif
        /// <summary>Extension of residence address, usually apartment or suite number.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AddressStreet2 { get; set; }
#nullable restore
#else
        public string AddressStreet2 { get; set; }
#endif
        /// <summary>State or subdivision of residence address. In the US, this should be the unabbreviated name. Not all international addresses use this attribute.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AddressSubdivision { get; set; }
#nullable restore
#else
        public string AddressSubdivision { get; set; }
#endif
        /// <summary>Birthdate, must be in the format &quot;YYYY-MM-DD&quot;.</summary>
        public Date? Birthdate { get; set; }
        /// <summary>ISO 3166-1 alpha 2 country code.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CountryCode { get; set; }
#nullable restore
#else
        public string CountryCode { get; set; }
#endif
        /// <summary>Email address.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EmailAddress { get; set; }
#nullable restore
#else
        public string EmailAddress { get; set; }
#endif
        /// <summary>JSON key-value pairs of field name to field value. Schema is defined by your Account Type.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Persona.OpenApiClient.Models.CreateAnAccount_data_attributes_fields? Fields { get; set; }
#nullable restore
#else
        public global::Soenneker.Persona.OpenApiClient.Models.CreateAnAccount_data_attributes_fields Fields { get; set; }
#endif
        /// <summary>Given or first name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NameFirst { get; set; }
#nullable restore
#else
        public string NameFirst { get; set; }
#endif
        /// <summary>Family or last name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NameLast { get; set; }
#nullable restore
#else
        public string NameLast { get; set; }
#endif
        /// <summary>Middle name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NameMiddle { get; set; }
#nullable restore
#else
        public string NameMiddle { get; set; }
#endif
        /// <summary>Phone number.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PhoneNumber { get; set; }
#nullable restore
#else
        public string PhoneNumber { get; set; }
#endif
        /// <summary>Reference ID on Account, refers to an entity in your user model</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ReferenceId { get; set; }
#nullable restore
#else
        public string ReferenceId { get; set; }
#endif
        /// <summary>Selfie photo.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Persona.OpenApiClient.Models.CreateAnAccount_data_attributes_selfiePhoto? SelfiePhoto { get; set; }
#nullable restore
#else
        public global::Soenneker.Persona.OpenApiClient.Models.CreateAnAccount_data_attributes_selfiePhoto SelfiePhoto { get; set; }
#endif
        /// <summary>Social security number.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SocialSecurityNumber { get; set; }
#nullable restore
#else
        public string SocialSecurityNumber { get; set; }
#endif
        /// <summary>A list of tag names to be associated with the Account.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Tags { get; set; }
#nullable restore
#else
        public List<string> Tags { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Persona.OpenApiClient.Models.CreateAnAccount_data_attributes"/> and sets the default values.
        /// </summary>
        public CreateAnAccount_data_attributes()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Persona.OpenApiClient.Models.CreateAnAccount_data_attributes"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Persona.OpenApiClient.Models.CreateAnAccount_data_attributes CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Persona.OpenApiClient.Models.CreateAnAccount_data_attributes();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "account-status", n => { AccountStatus = n.GetStringValue(); } },
                { "account-type-id", n => { AccountTypeId = n.GetStringValue(); } },
                { "address-city", n => { AddressCity = n.GetStringValue(); } },
                { "address-postal-code", n => { AddressPostalCode = n.GetStringValue(); } },
                { "address-street-1", n => { AddressStreet1 = n.GetStringValue(); } },
                { "address-street-2", n => { AddressStreet2 = n.GetStringValue(); } },
                { "address-subdivision", n => { AddressSubdivision = n.GetStringValue(); } },
                { "birthdate", n => { Birthdate = n.GetDateValue(); } },
                { "country-code", n => { CountryCode = n.GetStringValue(); } },
                { "email-address", n => { EmailAddress = n.GetStringValue(); } },
                { "fields", n => { Fields = n.GetObjectValue<global::Soenneker.Persona.OpenApiClient.Models.CreateAnAccount_data_attributes_fields>(global::Soenneker.Persona.OpenApiClient.Models.CreateAnAccount_data_attributes_fields.CreateFromDiscriminatorValue); } },
                { "name-first", n => { NameFirst = n.GetStringValue(); } },
                { "name-last", n => { NameLast = n.GetStringValue(); } },
                { "name-middle", n => { NameMiddle = n.GetStringValue(); } },
                { "phone-number", n => { PhoneNumber = n.GetStringValue(); } },
                { "reference-id", n => { ReferenceId = n.GetStringValue(); } },
                { "selfie-photo", n => { SelfiePhoto = n.GetObjectValue<global::Soenneker.Persona.OpenApiClient.Models.CreateAnAccount_data_attributes_selfiePhoto>(global::Soenneker.Persona.OpenApiClient.Models.CreateAnAccount_data_attributes_selfiePhoto.CreateFromDiscriminatorValue); } },
                { "social-security-number", n => { SocialSecurityNumber = n.GetStringValue(); } },
                { "tags", n => { Tags = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("account-status", AccountStatus);
            writer.WriteStringValue("account-type-id", AccountTypeId);
            writer.WriteStringValue("address-city", AddressCity);
            writer.WriteStringValue("address-postal-code", AddressPostalCode);
            writer.WriteStringValue("address-street-1", AddressStreet1);
            writer.WriteStringValue("address-street-2", AddressStreet2);
            writer.WriteStringValue("address-subdivision", AddressSubdivision);
            writer.WriteDateValue("birthdate", Birthdate);
            writer.WriteStringValue("country-code", CountryCode);
            writer.WriteStringValue("email-address", EmailAddress);
            writer.WriteObjectValue<global::Soenneker.Persona.OpenApiClient.Models.CreateAnAccount_data_attributes_fields>("fields", Fields);
            writer.WriteStringValue("name-first", NameFirst);
            writer.WriteStringValue("name-last", NameLast);
            writer.WriteStringValue("name-middle", NameMiddle);
            writer.WriteStringValue("phone-number", PhoneNumber);
            writer.WriteStringValue("reference-id", ReferenceId);
            writer.WriteObjectValue<global::Soenneker.Persona.OpenApiClient.Models.CreateAnAccount_data_attributes_selfiePhoto>("selfie-photo", SelfiePhoto);
            writer.WriteStringValue("social-security-number", SocialSecurityNumber);
            writer.WriteCollectionOfPrimitiveValues<string>("tags", Tags);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
