// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Persona.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class DeploymentRouteCriteriaOneOf4OriginOneOf2 : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The platform resource type the origin targets.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ResourceType { get; set; }
#nullable restore
#else
        public string ResourceType { get; set; }
#endif
        /// <summary>The token of the resource template the origin targets.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TemplateId { get; set; }
#nullable restore
#else
        public string TemplateId { get; set; }
#endif
        /// <summary>The version property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Persona.OpenApiClient.Models.DeploymentRouteCriteriaOneOf4OriginOneOf2Version? Version { get; set; }
#nullable restore
#else
        public global::Soenneker.Persona.OpenApiClient.Models.DeploymentRouteCriteriaOneOf4OriginOneOf2Version Version { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Persona.OpenApiClient.Models.DeploymentRouteCriteriaOneOf4OriginOneOf2"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Persona.OpenApiClient.Models.DeploymentRouteCriteriaOneOf4OriginOneOf2 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Persona.OpenApiClient.Models.DeploymentRouteCriteriaOneOf4OriginOneOf2();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "resource-type", n => { ResourceType = n.GetStringValue(); } },
                { "template-id", n => { TemplateId = n.GetStringValue(); } },
                { "version", n => { Version = n.GetObjectValue<global::Soenneker.Persona.OpenApiClient.Models.DeploymentRouteCriteriaOneOf4OriginOneOf2Version>(global::Soenneker.Persona.OpenApiClient.Models.DeploymentRouteCriteriaOneOf4OriginOneOf2Version.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("resource-type", ResourceType);
            writer.WriteStringValue("template-id", TemplateId);
            writer.WriteObjectValue<global::Soenneker.Persona.OpenApiClient.Models.DeploymentRouteCriteriaOneOf4OriginOneOf2Version>("version", Version);
        }
    }
}
#pragma warning restore CS0618
