// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Persona.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Document_government_id_attributes : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>City of residence address. Not all international addresses use this attribute.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AddressCity { get; set; }
#nullable restore
#else
        public string AddressCity { get; set; }
#endif
        /// <summary>ZIP or postal code of residence address. Not all international addresses use this attribute.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AddressPostalCode { get; set; }
#nullable restore
#else
        public string AddressPostalCode { get; set; }
#endif
        /// <summary>Street name of residence address.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AddressStreet1 { get; set; }
#nullable restore
#else
        public string AddressStreet1 { get; set; }
#endif
        /// <summary>Extension of residence address, usually apartment or suite number.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AddressStreet2 { get; set; }
#nullable restore
#else
        public string AddressStreet2 { get; set; }
#endif
        /// <summary>State or subdivision of residence address. In the US, this should be the unabbreviated name. Not all international addresses use this attribute.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AddressSubdivision { get; set; }
#nullable restore
#else
        public string AddressSubdivision { get; set; }
#endif
        /// <summary>The backPhoto property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Persona.OpenApiClient.Models.FileObject? BackPhoto { get; set; }
#nullable restore
#else
        public global::Soenneker.Persona.OpenApiClient.Models.FileObject BackPhoto { get; set; }
#endif
        /// <summary>The birthdate property</summary>
        public Date? Birthdate { get; set; }
        /// <summary>The birthplace property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Birthplace { get; set; }
#nullable restore
#else
        public string Birthplace { get; set; }
#endif
        /// <summary>The createdAt property</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The designations property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Designations { get; set; }
#nullable restore
#else
        public List<string> Designations { get; set; }
#endif
        /// <summary>The documentNumber property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DocumentNumber { get; set; }
#nullable restore
#else
        public string DocumentNumber { get; set; }
#endif
        /// <summary>The endorsements property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Endorsements { get; set; }
#nullable restore
#else
        public string Endorsements { get; set; }
#endif
        /// <summary>The expirationDate property</summary>
        public Date? ExpirationDate { get; set; }
        /// <summary>The frontPhoto property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Persona.OpenApiClient.Models.FileObject? FrontPhoto { get; set; }
#nullable restore
#else
        public global::Soenneker.Persona.OpenApiClient.Models.FileObject FrontPhoto { get; set; }
#endif
        /// <summary>The height property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Height { get; set; }
#nullable restore
#else
        public string Height { get; set; }
#endif
        /// <summary>The idClass property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? IdClass { get; set; }
#nullable restore
#else
        public string IdClass { get; set; }
#endif
        /// <summary>The identificationNumber property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? IdentificationNumber { get; set; }
#nullable restore
#else
        public string IdentificationNumber { get; set; }
#endif
        /// <summary>The issueDate property</summary>
        public Date? IssueDate { get; set; }
        /// <summary>The issuingAuthority property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? IssuingAuthority { get; set; }
#nullable restore
#else
        public string IssuingAuthority { get; set; }
#endif
        /// <summary>The issuingSubdivision property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? IssuingSubdivision { get; set; }
#nullable restore
#else
        public string IssuingSubdivision { get; set; }
#endif
        /// <summary>Given or first name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NameFirst { get; set; }
#nullable restore
#else
        public string NameFirst { get; set; }
#endif
        /// <summary>Family or last name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NameLast { get; set; }
#nullable restore
#else
        public string NameLast { get; set; }
#endif
        /// <summary>Middle name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NameMiddle { get; set; }
#nullable restore
#else
        public string NameMiddle { get; set; }
#endif
        /// <summary>The nameSuffix property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NameSuffix { get; set; }
#nullable restore
#else
        public string NameSuffix { get; set; }
#endif
        /// <summary>The nationality property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Nationality { get; set; }
#nullable restore
#else
        public string Nationality { get; set; }
#endif
        /// <summary>Native script given or first name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NativeNameFirst { get; set; }
#nullable restore
#else
        public string NativeNameFirst { get; set; }
#endif
        /// <summary>Native script family or last name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NativeNameLast { get; set; }
#nullable restore
#else
        public string NativeNameLast { get; set; }
#endif
        /// <summary>Native script middle name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NativeNameMiddle { get; set; }
#nullable restore
#else
        public string NativeNameMiddle { get; set; }
#endif
        /// <summary>Native script name title or prefix.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NativeNameTitle { get; set; }
#nullable restore
#else
        public string NativeNameTitle { get; set; }
#endif
        /// <summary>The processedAt property</summary>
        public DateTimeOffset? ProcessedAt { get; set; }
        /// <summary>The processedAtTs property</summary>
        public int? ProcessedAtTs { get; set; }
        /// <summary>The restrictions property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Restrictions { get; set; }
#nullable restore
#else
        public string Restrictions { get; set; }
#endif
        /// <summary>The selfiePhoto property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Persona.OpenApiClient.Models.FileObject? SelfiePhoto { get; set; }
#nullable restore
#else
        public global::Soenneker.Persona.OpenApiClient.Models.FileObject SelfiePhoto { get; set; }
#endif
        /// <summary>The sex property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Sex { get; set; }
#nullable restore
#else
        public string Sex { get; set; }
#endif
        /// <summary>Possible values:- initiated- submitted- processed- erroredDo not assume this is a static enumeration; Persona may add new values inthe future without a versioned update.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>The vehicleClass property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? VehicleClass { get; set; }
#nullable restore
#else
        public string VehicleClass { get; set; }
#endif
        /// <summary>The visaStatus property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? VisaStatus { get; set; }
#nullable restore
#else
        public string VisaStatus { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Persona.OpenApiClient.Models.Document_government_id_attributes"/> and sets the default values.
        /// </summary>
        public Document_government_id_attributes()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Persona.OpenApiClient.Models.Document_government_id_attributes"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Persona.OpenApiClient.Models.Document_government_id_attributes CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Persona.OpenApiClient.Models.Document_government_id_attributes();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "address-city", n => { AddressCity = n.GetStringValue(); } },
                { "address-postal-code", n => { AddressPostalCode = n.GetStringValue(); } },
                { "address-street-1", n => { AddressStreet1 = n.GetStringValue(); } },
                { "address-street-2", n => { AddressStreet2 = n.GetStringValue(); } },
                { "address-subdivision", n => { AddressSubdivision = n.GetStringValue(); } },
                { "back-photo", n => { BackPhoto = n.GetObjectValue<global::Soenneker.Persona.OpenApiClient.Models.FileObject>(global::Soenneker.Persona.OpenApiClient.Models.FileObject.CreateFromDiscriminatorValue); } },
                { "birthdate", n => { Birthdate = n.GetDateValue(); } },
                { "birthplace", n => { Birthplace = n.GetStringValue(); } },
                { "created-at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "designations", n => { Designations = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "document-number", n => { DocumentNumber = n.GetStringValue(); } },
                { "endorsements", n => { Endorsements = n.GetStringValue(); } },
                { "expiration-date", n => { ExpirationDate = n.GetDateValue(); } },
                { "front-photo", n => { FrontPhoto = n.GetObjectValue<global::Soenneker.Persona.OpenApiClient.Models.FileObject>(global::Soenneker.Persona.OpenApiClient.Models.FileObject.CreateFromDiscriminatorValue); } },
                { "height", n => { Height = n.GetStringValue(); } },
                { "id-class", n => { IdClass = n.GetStringValue(); } },
                { "identification-number", n => { IdentificationNumber = n.GetStringValue(); } },
                { "issue-date", n => { IssueDate = n.GetDateValue(); } },
                { "issuing-authority", n => { IssuingAuthority = n.GetStringValue(); } },
                { "issuing-subdivision", n => { IssuingSubdivision = n.GetStringValue(); } },
                { "name-first", n => { NameFirst = n.GetStringValue(); } },
                { "name-last", n => { NameLast = n.GetStringValue(); } },
                { "name-middle", n => { NameMiddle = n.GetStringValue(); } },
                { "name-suffix", n => { NameSuffix = n.GetStringValue(); } },
                { "nationality", n => { Nationality = n.GetStringValue(); } },
                { "native-name-first", n => { NativeNameFirst = n.GetStringValue(); } },
                { "native-name-last", n => { NativeNameLast = n.GetStringValue(); } },
                { "native-name-middle", n => { NativeNameMiddle = n.GetStringValue(); } },
                { "native-name-title", n => { NativeNameTitle = n.GetStringValue(); } },
                { "processed-at", n => { ProcessedAt = n.GetDateTimeOffsetValue(); } },
                { "processed-at-ts", n => { ProcessedAtTs = n.GetIntValue(); } },
                { "restrictions", n => { Restrictions = n.GetStringValue(); } },
                { "selfie-photo", n => { SelfiePhoto = n.GetObjectValue<global::Soenneker.Persona.OpenApiClient.Models.FileObject>(global::Soenneker.Persona.OpenApiClient.Models.FileObject.CreateFromDiscriminatorValue); } },
                { "sex", n => { Sex = n.GetStringValue(); } },
                { "status", n => { Status = n.GetStringValue(); } },
                { "vehicle-class", n => { VehicleClass = n.GetStringValue(); } },
                { "visa-status", n => { VisaStatus = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("address-city", AddressCity);
            writer.WriteStringValue("address-postal-code", AddressPostalCode);
            writer.WriteStringValue("address-street-1", AddressStreet1);
            writer.WriteStringValue("address-street-2", AddressStreet2);
            writer.WriteStringValue("address-subdivision", AddressSubdivision);
            writer.WriteObjectValue<global::Soenneker.Persona.OpenApiClient.Models.FileObject>("back-photo", BackPhoto);
            writer.WriteDateValue("birthdate", Birthdate);
            writer.WriteStringValue("birthplace", Birthplace);
            writer.WriteDateTimeOffsetValue("created-at", CreatedAt);
            writer.WriteCollectionOfPrimitiveValues<string>("designations", Designations);
            writer.WriteStringValue("document-number", DocumentNumber);
            writer.WriteStringValue("endorsements", Endorsements);
            writer.WriteDateValue("expiration-date", ExpirationDate);
            writer.WriteObjectValue<global::Soenneker.Persona.OpenApiClient.Models.FileObject>("front-photo", FrontPhoto);
            writer.WriteStringValue("height", Height);
            writer.WriteStringValue("id-class", IdClass);
            writer.WriteStringValue("identification-number", IdentificationNumber);
            writer.WriteDateValue("issue-date", IssueDate);
            writer.WriteStringValue("issuing-authority", IssuingAuthority);
            writer.WriteStringValue("issuing-subdivision", IssuingSubdivision);
            writer.WriteStringValue("name-first", NameFirst);
            writer.WriteStringValue("name-last", NameLast);
            writer.WriteStringValue("name-middle", NameMiddle);
            writer.WriteStringValue("name-suffix", NameSuffix);
            writer.WriteStringValue("nationality", Nationality);
            writer.WriteStringValue("native-name-first", NativeNameFirst);
            writer.WriteStringValue("native-name-last", NativeNameLast);
            writer.WriteStringValue("native-name-middle", NativeNameMiddle);
            writer.WriteStringValue("native-name-title", NativeNameTitle);
            writer.WriteDateTimeOffsetValue("processed-at", ProcessedAt);
            writer.WriteIntValue("processed-at-ts", ProcessedAtTs);
            writer.WriteStringValue("restrictions", Restrictions);
            writer.WriteObjectValue<global::Soenneker.Persona.OpenApiClient.Models.FileObject>("selfie-photo", SelfiePhoto);
            writer.WriteStringValue("sex", Sex);
            writer.WriteStringValue("status", Status);
            writer.WriteStringValue("vehicle-class", VehicleClass);
            writer.WriteStringValue("visa-status", VisaStatus);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
