// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Persona.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class DocumentGenericAttributes : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The createdAt property</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The classification of the document if detected. If unable to be detected, this will be other.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DocumentType { get; set; }
#nullable restore
#else
        public string DocumentType { get; set; }
#endif
        /// <summary>A list of extractions resulting from processing the uploaded documents corresponding to the document&apos;s extraction configuration.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Persona.OpenApiClient.Models.ExtractionResponsesItem>? ExtractionResponses { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Persona.OpenApiClient.Models.ExtractionResponsesItem> ExtractionResponses { get; set; }
#endif
        /// <summary>JSON key-value pairs of field name to field value. Exact schema depends on the configuration of your template.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Persona.OpenApiClient.Models.DocumentGenericAttributesFields? Fields { get; set; }
#nullable restore
#else
        public global::Soenneker.Persona.OpenApiClient.Models.DocumentGenericAttributesFields Fields { get; set; }
#endif
        /// <summary>The files uploaded to the document for processing.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Persona.OpenApiClient.Models.FileObject>? Files { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Persona.OpenApiClient.Models.FileObject> Files { get; set; }
#endif
        /// <summary>The filesNormalized property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Persona.OpenApiClient.Models.FileObject>? FilesNormalized { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Persona.OpenApiClient.Models.FileObject> FilesNormalized { get; set; }
#endif
        /// <summary>The kind property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Kind { get; set; }
#nullable restore
#else
        public string Kind { get; set; }
#endif
        /// <summary>The processedAt property</summary>
        public DateTimeOffset? ProcessedAt { get; set; }
        /// <summary>The processedAtTs property</summary>
        public int? ProcessedAtTs { get; set; }
        /// <summary>Possible values:- initiated- submitted- processed- erroredDo not assume this is a static enumeration; Persona may add new values inthe future without a versioned update.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Persona.OpenApiClient.Models.DocumentGenericAttributes"/> and sets the default values.
        /// </summary>
        public DocumentGenericAttributes()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Persona.OpenApiClient.Models.DocumentGenericAttributes"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Persona.OpenApiClient.Models.DocumentGenericAttributes CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Persona.OpenApiClient.Models.DocumentGenericAttributes();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "created-at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "document-type", n => { DocumentType = n.GetStringValue(); } },
                { "extraction-responses", n => { ExtractionResponses = n.GetCollectionOfObjectValues<global::Soenneker.Persona.OpenApiClient.Models.ExtractionResponsesItem>(global::Soenneker.Persona.OpenApiClient.Models.ExtractionResponsesItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "fields", n => { Fields = n.GetObjectValue<global::Soenneker.Persona.OpenApiClient.Models.DocumentGenericAttributesFields>(global::Soenneker.Persona.OpenApiClient.Models.DocumentGenericAttributesFields.CreateFromDiscriminatorValue); } },
                { "files", n => { Files = n.GetCollectionOfObjectValues<global::Soenneker.Persona.OpenApiClient.Models.FileObject>(global::Soenneker.Persona.OpenApiClient.Models.FileObject.CreateFromDiscriminatorValue)?.AsList(); } },
                { "files-normalized", n => { FilesNormalized = n.GetCollectionOfObjectValues<global::Soenneker.Persona.OpenApiClient.Models.FileObject>(global::Soenneker.Persona.OpenApiClient.Models.FileObject.CreateFromDiscriminatorValue)?.AsList(); } },
                { "kind", n => { Kind = n.GetStringValue(); } },
                { "processed-at", n => { ProcessedAt = n.GetDateTimeOffsetValue(); } },
                { "processed-at-ts", n => { ProcessedAtTs = n.GetIntValue(); } },
                { "status", n => { Status = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("created-at", CreatedAt);
            writer.WriteStringValue("document-type", DocumentType);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Persona.OpenApiClient.Models.ExtractionResponsesItem>("extraction-responses", ExtractionResponses);
            writer.WriteObjectValue<global::Soenneker.Persona.OpenApiClient.Models.DocumentGenericAttributesFields>("fields", Fields);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Persona.OpenApiClient.Models.FileObject>("files", Files);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Persona.OpenApiClient.Models.FileObject>("files-normalized", FilesNormalized);
            writer.WriteStringValue("kind", Kind);
            writer.WriteDateTimeOffsetValue("processed-at", ProcessedAt);
            writer.WriteIntValue("processed-at-ts", ProcessedAtTs);
            writer.WriteStringValue("status", Status);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
