// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Persona.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Event_attributes : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Additional context populated for some event types.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Persona.OpenApiClient.Models.Event_attributes_context? Context { get; set; }
#nullable restore
#else
        public global::Soenneker.Persona.OpenApiClient.Models.Event_attributes_context Context { get; set; }
#endif
        /// <summary>The createdAt property</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The entire serialized entity that triggered the event</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Persona.OpenApiClient.Models.Event_attributes_payload? Payload { get; set; }
#nullable restore
#else
        public global::Soenneker.Persona.OpenApiClient.Models.Event_attributes_payload Payload { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Persona.OpenApiClient.Models.Event_attributes"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Persona.OpenApiClient.Models.Event_attributes CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Persona.OpenApiClient.Models.Event_attributes();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "context", n => { Context = n.GetObjectValue<global::Soenneker.Persona.OpenApiClient.Models.Event_attributes_context>(global::Soenneker.Persona.OpenApiClient.Models.Event_attributes_context.CreateFromDiscriminatorValue); } },
                { "created-at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "payload", n => { Payload = n.GetObjectValue<global::Soenneker.Persona.OpenApiClient.Models.Event_attributes_payload>(global::Soenneker.Persona.OpenApiClient.Models.Event_attributes_payload.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Persona.OpenApiClient.Models.Event_attributes_context>("context", Context);
            writer.WriteDateTimeOffsetValue("created-at", CreatedAt);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::Soenneker.Persona.OpenApiClient.Models.Event_attributes_payload>("payload", Payload);
        }
    }
}
#pragma warning restore CS0618
