// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Persona.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ImporterSharedAttributes : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The completedAt property</summary>
        public DateTimeOffset? CompletedAt { get; set; }
        /// <summary>The createdAt property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedAt { get; set; }
#nullable restore
#else
        public string CreatedAt { get; set; }
#endif
        /// <summary>The duplicateCount property</summary>
        public int? DuplicateCount { get; set; }
        /// <summary>The errorCount property</summary>
        public int? ErrorCount { get; set; }
        /// <summary>Possible values:- pending- ready- erroredDo not assume this is a static enumeration; Persona may add new valuesin the future without a versioned update.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>The successfulCount property</summary>
        public int? SuccessfulCount { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Persona.OpenApiClient.Models.ImporterSharedAttributes"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Persona.OpenApiClient.Models.ImporterSharedAttributes CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Persona.OpenApiClient.Models.ImporterSharedAttributes();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "completed-at", n => { CompletedAt = n.GetDateTimeOffsetValue(); } },
                { "created-at", n => { CreatedAt = n.GetStringValue(); } },
                { "duplicate-count", n => { DuplicateCount = n.GetIntValue(); } },
                { "error-count", n => { ErrorCount = n.GetIntValue(); } },
                { "status", n => { Status = n.GetStringValue(); } },
                { "successful-count", n => { SuccessfulCount = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("completed-at", CompletedAt);
            writer.WriteStringValue("created-at", CreatedAt);
            writer.WriteIntValue("duplicate-count", DuplicateCount);
            writer.WriteIntValue("error-count", ErrorCount);
            writer.WriteStringValue("status", Status);
            writer.WriteIntValue("successful-count", SuccessfulCount);
        }
    }
}
#pragma warning restore CS0618
