// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Persona.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ImportInquiryTemplateTranslationsRequestDataAttributesTranslationsItem : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The attributeName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AttributeName { get; set; }
#nullable restore
#else
        public string AttributeName { get; set; }
#endif
        /// <summary>The component property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Component { get; set; }
#nullable restore
#else
        public string Component { get; set; }
#endif
        /// <summary>The localeValues property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Persona.OpenApiClient.Models.ImportInquiryTemplateTranslationsRequestDataAttributesTranslationsItemLocaleValuesItem>? LocaleValues { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Persona.OpenApiClient.Models.ImportInquiryTemplateTranslationsRequestDataAttributesTranslationsItemLocaleValuesItem> LocaleValues { get; set; }
#endif
        /// <summary>The step property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Step { get; set; }
#nullable restore
#else
        public string Step { get; set; }
#endif
        /// <summary>The stepDisplayName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StepDisplayName { get; set; }
#nullable restore
#else
        public string StepDisplayName { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Persona.OpenApiClient.Models.ImportInquiryTemplateTranslationsRequestDataAttributesTranslationsItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Persona.OpenApiClient.Models.ImportInquiryTemplateTranslationsRequestDataAttributesTranslationsItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Persona.OpenApiClient.Models.ImportInquiryTemplateTranslationsRequestDataAttributesTranslationsItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "attribute-name", n => { AttributeName = n.GetStringValue(); } },
                { "component", n => { Component = n.GetStringValue(); } },
                { "locale-values", n => { LocaleValues = n.GetCollectionOfObjectValues<global::Soenneker.Persona.OpenApiClient.Models.ImportInquiryTemplateTranslationsRequestDataAttributesTranslationsItemLocaleValuesItem>(global::Soenneker.Persona.OpenApiClient.Models.ImportInquiryTemplateTranslationsRequestDataAttributesTranslationsItemLocaleValuesItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "step", n => { Step = n.GetStringValue(); } },
                { "step-display-name", n => { StepDisplayName = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("attribute-name", AttributeName);
            writer.WriteStringValue("component", Component);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Persona.OpenApiClient.Models.ImportInquiryTemplateTranslationsRequestDataAttributesTranslationsItemLocaleValuesItem>("locale-values", LocaleValues);
            writer.WriteStringValue("step", Step);
            writer.WriteStringValue("step-display-name", StepDisplayName);
        }
    }
}
#pragma warning restore CS0618
