// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Persona.OpenApiClient.Models
{
    /// <summary>
    /// &quot;Controls which related objects appear in the `included` array of webhook payloads. The default is `include_none`. When `state` is `custom`, `event-types` configures which related objects to include per event type: event types you are subscribed to (via `enabled-events`) but do not list are excluded, and event types you list but are not subscribed to are dropped on save. A `custom` config whose event types are all `[\&quot;*\&quot;]` is equivalent to, and is normalized to, `include_all`.&quot;
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class IncludedAllowlist : IAdditionalDataHolder, IComposedTypeWrapper, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Per-event-type include configuration. At most one entry per event type.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Persona.OpenApiClient.Models.IncludedAllowlistCustomEventTypesItem>? EventTypes { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Persona.OpenApiClient.Models.IncludedAllowlistCustomEventTypesItem> EventTypes { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Persona.OpenApiClient.Models.IncludedAllowlistCustom"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Persona.OpenApiClient.Models.IncludedAllowlistCustom? IncludedAllowlistCustom { get; set; }
#nullable restore
#else
        public global::Soenneker.Persona.OpenApiClient.Models.IncludedAllowlistCustom IncludedAllowlistCustom { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Persona.OpenApiClient.Models.IncludedAllowlistIncludeAll"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Persona.OpenApiClient.Models.IncludedAllowlistIncludeAll? IncludedAllowlistIncludeAll { get; set; }
#nullable restore
#else
        public global::Soenneker.Persona.OpenApiClient.Models.IncludedAllowlistIncludeAll IncludedAllowlistIncludeAll { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Persona.OpenApiClient.Models.IncludedAllowlistIncludeNone"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Persona.OpenApiClient.Models.IncludedAllowlistIncludeNone? IncludedAllowlistIncludeNone { get; set; }
#nullable restore
#else
        public global::Soenneker.Persona.OpenApiClient.Models.IncludedAllowlistIncludeNone IncludedAllowlistIncludeNone { get; set; }
#endif
        /// <summary>Include all related objects for every subscribed event type.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? State { get; set; }
#nullable restore
#else
        public string State { get; set; }
#endif
        /// <summary>Union discriminator</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Persona.OpenApiClient.Models.IncludedAllowlist"/> and sets the default values.
        /// </summary>
        public IncludedAllowlist()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Persona.OpenApiClient.Models.IncludedAllowlist"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Persona.OpenApiClient.Models.IncludedAllowlist CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            var result = new global::Soenneker.Persona.OpenApiClient.Models.IncludedAllowlist();
            if("IncludedAllowlistCustom".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.IncludedAllowlistCustom = new global::Soenneker.Persona.OpenApiClient.Models.IncludedAllowlistCustom();
            }
            else if("IncludedAllowlistIncludeAll".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.IncludedAllowlistIncludeAll = new global::Soenneker.Persona.OpenApiClient.Models.IncludedAllowlistIncludeAll();
            }
            else if("IncludedAllowlistIncludeNone".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.IncludedAllowlistIncludeNone = new global::Soenneker.Persona.OpenApiClient.Models.IncludedAllowlistIncludeNone();
            }
            else if(parseNode.GetStringValue() is string stateValue)
            {
                result.State = stateValue;
            }
            else if(parseNode.GetStringValue() is string typeValue)
            {
                result.Type = typeValue;
            }
            else if(parseNode.GetCollectionOfObjectValues<global::Soenneker.Persona.OpenApiClient.Models.IncludedAllowlistCustomEventTypesItem>(global::Soenneker.Persona.OpenApiClient.Models.IncludedAllowlistCustomEventTypesItem.CreateFromDiscriminatorValue)?.AsList() is List<global::Soenneker.Persona.OpenApiClient.Models.IncludedAllowlistCustomEventTypesItem> eventTypesValue)
            {
                result.EventTypes = eventTypesValue;
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(IncludedAllowlistCustom != null)
            {
                return IncludedAllowlistCustom.GetFieldDeserializers();
            }
            else if(IncludedAllowlistIncludeAll != null)
            {
                return IncludedAllowlistIncludeAll.GetFieldDeserializers();
            }
            else if(IncludedAllowlistIncludeNone != null)
            {
                return IncludedAllowlistIncludeNone.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(IncludedAllowlistCustom != null)
            {
                writer.WriteObjectValue<global::Soenneker.Persona.OpenApiClient.Models.IncludedAllowlistCustom>(null, IncludedAllowlistCustom);
            }
            else if(IncludedAllowlistIncludeAll != null)
            {
                writer.WriteObjectValue<global::Soenneker.Persona.OpenApiClient.Models.IncludedAllowlistIncludeAll>(null, IncludedAllowlistIncludeAll);
            }
            else if(IncludedAllowlistIncludeNone != null)
            {
                writer.WriteObjectValue<global::Soenneker.Persona.OpenApiClient.Models.IncludedAllowlistIncludeNone>(null, IncludedAllowlistIncludeNone);
            }
            else if(State != null)
            {
                writer.WriteStringValue(null, State);
            }
            else if(Type != null)
            {
                writer.WriteStringValue(null, Type);
            }
            else if(EventTypes != null)
            {
                writer.WriteCollectionOfObjectValues<global::Soenneker.Persona.OpenApiClient.Models.IncludedAllowlistCustomEventTypesItem>(null, EventTypes);
            }
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
