// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Persona.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum InquiryMarkedForReviewName
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "inquiry.marked-for-review")]
        #pragma warning disable CS1591
        InquiryMarkedForReview,
        #pragma warning restore CS1591
    }
}
