// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Persona.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum InquirySessionRelationshipsDevice_data_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "device")]
        #pragma warning disable CS1591
        Device,
        #pragma warning restore CS1591
    }
}
