// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Persona.OpenApiClient.Models
{
    /// <summary>
    /// JSON key-value pairs of field name to field value. Exact schema depends on the configuration of the Inquiry template for this Inquiry. Keys in `fields` are **not** key inflected.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Inquiry1AttributesFields : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>City of residence address. Not all international addresses use this attribute.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Persona.OpenApiClient.Models.Inquiry1AttributesFieldsAddressCity? AddressCity { get; set; }
#nullable restore
#else
        public global::Soenneker.Persona.OpenApiClient.Models.Inquiry1AttributesFieldsAddressCity AddressCity { get; set; }
#endif
        /// <summary>ISO 3166-1 alpha 2 country code.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Persona.OpenApiClient.Models.Inquiry1AttributesFieldsAddressCountryCode? AddressCountryCode { get; set; }
#nullable restore
#else
        public global::Soenneker.Persona.OpenApiClient.Models.Inquiry1AttributesFieldsAddressCountryCode AddressCountryCode { get; set; }
#endif
        /// <summary>ZIP or postal code of residence address. Not all international addresses use this attribute.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Persona.OpenApiClient.Models.Inquiry1AttributesFieldsAddressPostalCode? AddressPostalCode { get; set; }
#nullable restore
#else
        public global::Soenneker.Persona.OpenApiClient.Models.Inquiry1AttributesFieldsAddressPostalCode AddressPostalCode { get; set; }
#endif
        /// <summary>The addressStreet1 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Persona.OpenApiClient.Models.Inquiry1AttributesFieldsAddressStreet1? AddressStreet1 { get; set; }
#nullable restore
#else
        public global::Soenneker.Persona.OpenApiClient.Models.Inquiry1AttributesFieldsAddressStreet1 AddressStreet1 { get; set; }
#endif
        /// <summary>The addressStreet2 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Persona.OpenApiClient.Models.Inquiry1AttributesFieldsAddressStreet2? AddressStreet2 { get; set; }
#nullable restore
#else
        public global::Soenneker.Persona.OpenApiClient.Models.Inquiry1AttributesFieldsAddressStreet2 AddressStreet2 { get; set; }
#endif
        /// <summary>State or subdivision of residence address. In the US, this should be the unabbreviated name. Not all international addresses use this attribute.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Persona.OpenApiClient.Models.Inquiry1AttributesFieldsAddressSubdivision? AddressSubdivision { get; set; }
#nullable restore
#else
        public global::Soenneker.Persona.OpenApiClient.Models.Inquiry1AttributesFieldsAddressSubdivision AddressSubdivision { get; set; }
#endif
        /// <summary>The birthdate property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Persona.OpenApiClient.Models.Inquiry1AttributesFieldsBirthdate? Birthdate { get; set; }
#nullable restore
#else
        public global::Soenneker.Persona.OpenApiClient.Models.Inquiry1AttributesFieldsBirthdate Birthdate { get; set; }
#endif
        /// <summary>The emailAddress property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Persona.OpenApiClient.Models.Inquiry1AttributesFieldsEmailAddress? EmailAddress { get; set; }
#nullable restore
#else
        public global::Soenneker.Persona.OpenApiClient.Models.Inquiry1AttributesFieldsEmailAddress EmailAddress { get; set; }
#endif
        /// <summary>The identificationNumber property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Persona.OpenApiClient.Models.Inquiry1AttributesFieldsIdentificationNumber? IdentificationNumber { get; set; }
#nullable restore
#else
        public global::Soenneker.Persona.OpenApiClient.Models.Inquiry1AttributesFieldsIdentificationNumber IdentificationNumber { get; set; }
#endif
        /// <summary>The nameFirst property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Persona.OpenApiClient.Models.Inquiry1AttributesFieldsNameFirst? NameFirst { get; set; }
#nullable restore
#else
        public global::Soenneker.Persona.OpenApiClient.Models.Inquiry1AttributesFieldsNameFirst NameFirst { get; set; }
#endif
        /// <summary>The nameLast property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Persona.OpenApiClient.Models.Inquiry1AttributesFieldsNameLast? NameLast { get; set; }
#nullable restore
#else
        public global::Soenneker.Persona.OpenApiClient.Models.Inquiry1AttributesFieldsNameLast NameLast { get; set; }
#endif
        /// <summary>The nameMiddle property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Persona.OpenApiClient.Models.Inquiry1AttributesFieldsNameMiddle? NameMiddle { get; set; }
#nullable restore
#else
        public global::Soenneker.Persona.OpenApiClient.Models.Inquiry1AttributesFieldsNameMiddle NameMiddle { get; set; }
#endif
        /// <summary>The phoneNumber property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Persona.OpenApiClient.Models.Inquiry1AttributesFieldsPhoneNumber? PhoneNumber { get; set; }
#nullable restore
#else
        public global::Soenneker.Persona.OpenApiClient.Models.Inquiry1AttributesFieldsPhoneNumber PhoneNumber { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Persona.OpenApiClient.Models.Inquiry1AttributesFields"/> and sets the default values.
        /// </summary>
        public Inquiry1AttributesFields()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Persona.OpenApiClient.Models.Inquiry1AttributesFields"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Persona.OpenApiClient.Models.Inquiry1AttributesFields CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Persona.OpenApiClient.Models.Inquiry1AttributesFields();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "address-city", n => { AddressCity = n.GetObjectValue<global::Soenneker.Persona.OpenApiClient.Models.Inquiry1AttributesFieldsAddressCity>(global::Soenneker.Persona.OpenApiClient.Models.Inquiry1AttributesFieldsAddressCity.CreateFromDiscriminatorValue); } },
                { "address-country-code", n => { AddressCountryCode = n.GetObjectValue<global::Soenneker.Persona.OpenApiClient.Models.Inquiry1AttributesFieldsAddressCountryCode>(global::Soenneker.Persona.OpenApiClient.Models.Inquiry1AttributesFieldsAddressCountryCode.CreateFromDiscriminatorValue); } },
                { "address-postal-code", n => { AddressPostalCode = n.GetObjectValue<global::Soenneker.Persona.OpenApiClient.Models.Inquiry1AttributesFieldsAddressPostalCode>(global::Soenneker.Persona.OpenApiClient.Models.Inquiry1AttributesFieldsAddressPostalCode.CreateFromDiscriminatorValue); } },
                { "address-street-1", n => { AddressStreet1 = n.GetObjectValue<global::Soenneker.Persona.OpenApiClient.Models.Inquiry1AttributesFieldsAddressStreet1>(global::Soenneker.Persona.OpenApiClient.Models.Inquiry1AttributesFieldsAddressStreet1.CreateFromDiscriminatorValue); } },
                { "address-street-2", n => { AddressStreet2 = n.GetObjectValue<global::Soenneker.Persona.OpenApiClient.Models.Inquiry1AttributesFieldsAddressStreet2>(global::Soenneker.Persona.OpenApiClient.Models.Inquiry1AttributesFieldsAddressStreet2.CreateFromDiscriminatorValue); } },
                { "address-subdivision", n => { AddressSubdivision = n.GetObjectValue<global::Soenneker.Persona.OpenApiClient.Models.Inquiry1AttributesFieldsAddressSubdivision>(global::Soenneker.Persona.OpenApiClient.Models.Inquiry1AttributesFieldsAddressSubdivision.CreateFromDiscriminatorValue); } },
                { "birthdate", n => { Birthdate = n.GetObjectValue<global::Soenneker.Persona.OpenApiClient.Models.Inquiry1AttributesFieldsBirthdate>(global::Soenneker.Persona.OpenApiClient.Models.Inquiry1AttributesFieldsBirthdate.CreateFromDiscriminatorValue); } },
                { "email-address", n => { EmailAddress = n.GetObjectValue<global::Soenneker.Persona.OpenApiClient.Models.Inquiry1AttributesFieldsEmailAddress>(global::Soenneker.Persona.OpenApiClient.Models.Inquiry1AttributesFieldsEmailAddress.CreateFromDiscriminatorValue); } },
                { "identification-number", n => { IdentificationNumber = n.GetObjectValue<global::Soenneker.Persona.OpenApiClient.Models.Inquiry1AttributesFieldsIdentificationNumber>(global::Soenneker.Persona.OpenApiClient.Models.Inquiry1AttributesFieldsIdentificationNumber.CreateFromDiscriminatorValue); } },
                { "name-first", n => { NameFirst = n.GetObjectValue<global::Soenneker.Persona.OpenApiClient.Models.Inquiry1AttributesFieldsNameFirst>(global::Soenneker.Persona.OpenApiClient.Models.Inquiry1AttributesFieldsNameFirst.CreateFromDiscriminatorValue); } },
                { "name-last", n => { NameLast = n.GetObjectValue<global::Soenneker.Persona.OpenApiClient.Models.Inquiry1AttributesFieldsNameLast>(global::Soenneker.Persona.OpenApiClient.Models.Inquiry1AttributesFieldsNameLast.CreateFromDiscriminatorValue); } },
                { "name-middle", n => { NameMiddle = n.GetObjectValue<global::Soenneker.Persona.OpenApiClient.Models.Inquiry1AttributesFieldsNameMiddle>(global::Soenneker.Persona.OpenApiClient.Models.Inquiry1AttributesFieldsNameMiddle.CreateFromDiscriminatorValue); } },
                { "phone-number", n => { PhoneNumber = n.GetObjectValue<global::Soenneker.Persona.OpenApiClient.Models.Inquiry1AttributesFieldsPhoneNumber>(global::Soenneker.Persona.OpenApiClient.Models.Inquiry1AttributesFieldsPhoneNumber.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Persona.OpenApiClient.Models.Inquiry1AttributesFieldsAddressCity>("address-city", AddressCity);
            writer.WriteObjectValue<global::Soenneker.Persona.OpenApiClient.Models.Inquiry1AttributesFieldsAddressCountryCode>("address-country-code", AddressCountryCode);
            writer.WriteObjectValue<global::Soenneker.Persona.OpenApiClient.Models.Inquiry1AttributesFieldsAddressPostalCode>("address-postal-code", AddressPostalCode);
            writer.WriteObjectValue<global::Soenneker.Persona.OpenApiClient.Models.Inquiry1AttributesFieldsAddressStreet1>("address-street-1", AddressStreet1);
            writer.WriteObjectValue<global::Soenneker.Persona.OpenApiClient.Models.Inquiry1AttributesFieldsAddressStreet2>("address-street-2", AddressStreet2);
            writer.WriteObjectValue<global::Soenneker.Persona.OpenApiClient.Models.Inquiry1AttributesFieldsAddressSubdivision>("address-subdivision", AddressSubdivision);
            writer.WriteObjectValue<global::Soenneker.Persona.OpenApiClient.Models.Inquiry1AttributesFieldsBirthdate>("birthdate", Birthdate);
            writer.WriteObjectValue<global::Soenneker.Persona.OpenApiClient.Models.Inquiry1AttributesFieldsEmailAddress>("email-address", EmailAddress);
            writer.WriteObjectValue<global::Soenneker.Persona.OpenApiClient.Models.Inquiry1AttributesFieldsIdentificationNumber>("identification-number", IdentificationNumber);
            writer.WriteObjectValue<global::Soenneker.Persona.OpenApiClient.Models.Inquiry1AttributesFieldsNameFirst>("name-first", NameFirst);
            writer.WriteObjectValue<global::Soenneker.Persona.OpenApiClient.Models.Inquiry1AttributesFieldsNameLast>("name-last", NameLast);
            writer.WriteObjectValue<global::Soenneker.Persona.OpenApiClient.Models.Inquiry1AttributesFieldsNameMiddle>("name-middle", NameMiddle);
            writer.WriteObjectValue<global::Soenneker.Persona.OpenApiClient.Models.Inquiry1AttributesFieldsPhoneNumber>("phone-number", PhoneNumber);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
