// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Persona.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Inquiry_template_relationships_latestPublishedVersion_data_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "inquiry-template-version")]
        #pragma warning disable CS1591
        InquiryTemplateVersion,
        #pragma warning restore CS1591
    }
}
