// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Persona.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class InquiryTemplateAttributes : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>List of domains allowed for embedded flows</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? EmbeddedFlowDomainAllowlist { get; set; }
#nullable restore
#else
        public List<string> EmbeddedFlowDomainAllowlist { get; set; }
#endif
        /// <summary>An allowlist that specifies the URI schemes for redirect after completion of a Hosted Flow.This can be used to implement deep linking for mobile integrations. If this list is empty,all URLs with the URI scheme http or https are allowed.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? HostedFlowRedirectUriSchemes { get; set; }
#nullable restore
#else
        public List<string> HostedFlowRedirectUriSchemes { get; set; }
#endif
        /// <summary>The subdomain that your hosted flow can be hosted on (e.g. &quot;mycompany.withpersona.com&quot;)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? HostedFlowSubdomains { get; set; }
#nullable restore
#else
        public List<string> HostedFlowSubdomains { get; set; }
#endif
        /// <summary>Name of the Inquiry Template</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Possible values:- active- inactiveDo not assume this is a static enumeration; Persona may add new valuesin the future without a versioned update.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Persona.OpenApiClient.Models.InquiryTemplateAttributes"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Persona.OpenApiClient.Models.InquiryTemplateAttributes CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Persona.OpenApiClient.Models.InquiryTemplateAttributes();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "embedded-flow-domain-allowlist", n => { EmbeddedFlowDomainAllowlist = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "hosted-flow-redirect-uri-schemes", n => { HostedFlowRedirectUriSchemes = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "hosted-flow-subdomains", n => { HostedFlowSubdomains = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "status", n => { Status = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<string>("embedded-flow-domain-allowlist", EmbeddedFlowDomainAllowlist);
            writer.WriteCollectionOfPrimitiveValues<string>("hosted-flow-redirect-uri-schemes", HostedFlowRedirectUriSchemes);
            writer.WriteCollectionOfPrimitiveValues<string>("hosted-flow-subdomains", HostedFlowSubdomains);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("status", Status);
        }
    }
}
#pragma warning restore CS0618
