// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Persona.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Persona.OpenApiClient.Models.ListItemGeolocationRelationshipsCreatorDataMember1"/>, <see cref="global::Soenneker.Persona.OpenApiClient.Models.ListItemGeolocationRelationshipsCreatorDataMember2"/>, <see cref="global::Soenneker.Persona.OpenApiClient.Models.ListItemGeolocationRelationshipsCreatorDataMember3"/>, <see cref="global::Soenneker.Persona.OpenApiClient.Models.ListItemGeolocationRelationshipsCreatorDataMember4"/>, <see cref="global::Soenneker.Persona.OpenApiClient.Models.ListItemGeolocationRelationshipsCreatorDataMember5"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ListItemGeolocationRelationshipsCreatorData : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Persona.OpenApiClient.Models.ListItemGeolocationRelationshipsCreatorDataMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Persona.OpenApiClient.Models.ListItemGeolocationRelationshipsCreatorDataMember1? ListItemGeolocationRelationshipsCreatorDataMember1 { get; set; }
#nullable restore
#else
        public global::Soenneker.Persona.OpenApiClient.Models.ListItemGeolocationRelationshipsCreatorDataMember1 ListItemGeolocationRelationshipsCreatorDataMember1 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Persona.OpenApiClient.Models.ListItemGeolocationRelationshipsCreatorDataMember2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Persona.OpenApiClient.Models.ListItemGeolocationRelationshipsCreatorDataMember2? ListItemGeolocationRelationshipsCreatorDataMember2 { get; set; }
#nullable restore
#else
        public global::Soenneker.Persona.OpenApiClient.Models.ListItemGeolocationRelationshipsCreatorDataMember2 ListItemGeolocationRelationshipsCreatorDataMember2 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Persona.OpenApiClient.Models.ListItemGeolocationRelationshipsCreatorDataMember3"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Persona.OpenApiClient.Models.ListItemGeolocationRelationshipsCreatorDataMember3? ListItemGeolocationRelationshipsCreatorDataMember3 { get; set; }
#nullable restore
#else
        public global::Soenneker.Persona.OpenApiClient.Models.ListItemGeolocationRelationshipsCreatorDataMember3 ListItemGeolocationRelationshipsCreatorDataMember3 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Persona.OpenApiClient.Models.ListItemGeolocationRelationshipsCreatorDataMember4"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Persona.OpenApiClient.Models.ListItemGeolocationRelationshipsCreatorDataMember4? ListItemGeolocationRelationshipsCreatorDataMember4 { get; set; }
#nullable restore
#else
        public global::Soenneker.Persona.OpenApiClient.Models.ListItemGeolocationRelationshipsCreatorDataMember4 ListItemGeolocationRelationshipsCreatorDataMember4 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Persona.OpenApiClient.Models.ListItemGeolocationRelationshipsCreatorDataMember5"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Persona.OpenApiClient.Models.ListItemGeolocationRelationshipsCreatorDataMember5? ListItemGeolocationRelationshipsCreatorDataMember5 { get; set; }
#nullable restore
#else
        public global::Soenneker.Persona.OpenApiClient.Models.ListItemGeolocationRelationshipsCreatorDataMember5 ListItemGeolocationRelationshipsCreatorDataMember5 { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Persona.OpenApiClient.Models.ListItemGeolocationRelationshipsCreatorData"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Persona.OpenApiClient.Models.ListItemGeolocationRelationshipsCreatorData CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            var result = new global::Soenneker.Persona.OpenApiClient.Models.ListItemGeolocationRelationshipsCreatorData();
            if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ListItemGeolocationRelationshipsCreatorDataMember1 = new global::Soenneker.Persona.OpenApiClient.Models.ListItemGeolocationRelationshipsCreatorDataMember1();
            }
            else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ListItemGeolocationRelationshipsCreatorDataMember2 = new global::Soenneker.Persona.OpenApiClient.Models.ListItemGeolocationRelationshipsCreatorDataMember2();
            }
            else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ListItemGeolocationRelationshipsCreatorDataMember3 = new global::Soenneker.Persona.OpenApiClient.Models.ListItemGeolocationRelationshipsCreatorDataMember3();
            }
            else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ListItemGeolocationRelationshipsCreatorDataMember4 = new global::Soenneker.Persona.OpenApiClient.Models.ListItemGeolocationRelationshipsCreatorDataMember4();
            }
            else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ListItemGeolocationRelationshipsCreatorDataMember5 = new global::Soenneker.Persona.OpenApiClient.Models.ListItemGeolocationRelationshipsCreatorDataMember5();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(ListItemGeolocationRelationshipsCreatorDataMember1 != null)
            {
                return ListItemGeolocationRelationshipsCreatorDataMember1.GetFieldDeserializers();
            }
            else if(ListItemGeolocationRelationshipsCreatorDataMember2 != null)
            {
                return ListItemGeolocationRelationshipsCreatorDataMember2.GetFieldDeserializers();
            }
            else if(ListItemGeolocationRelationshipsCreatorDataMember3 != null)
            {
                return ListItemGeolocationRelationshipsCreatorDataMember3.GetFieldDeserializers();
            }
            else if(ListItemGeolocationRelationshipsCreatorDataMember4 != null)
            {
                return ListItemGeolocationRelationshipsCreatorDataMember4.GetFieldDeserializers();
            }
            else if(ListItemGeolocationRelationshipsCreatorDataMember5 != null)
            {
                return ListItemGeolocationRelationshipsCreatorDataMember5.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(ListItemGeolocationRelationshipsCreatorDataMember1 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Persona.OpenApiClient.Models.ListItemGeolocationRelationshipsCreatorDataMember1>(null, ListItemGeolocationRelationshipsCreatorDataMember1);
            }
            else if(ListItemGeolocationRelationshipsCreatorDataMember2 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Persona.OpenApiClient.Models.ListItemGeolocationRelationshipsCreatorDataMember2>(null, ListItemGeolocationRelationshipsCreatorDataMember2);
            }
            else if(ListItemGeolocationRelationshipsCreatorDataMember3 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Persona.OpenApiClient.Models.ListItemGeolocationRelationshipsCreatorDataMember3>(null, ListItemGeolocationRelationshipsCreatorDataMember3);
            }
            else if(ListItemGeolocationRelationshipsCreatorDataMember4 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Persona.OpenApiClient.Models.ListItemGeolocationRelationshipsCreatorDataMember4>(null, ListItemGeolocationRelationshipsCreatorDataMember4);
            }
            else if(ListItemGeolocationRelationshipsCreatorDataMember5 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Persona.OpenApiClient.Models.ListItemGeolocationRelationshipsCreatorDataMember5>(null, ListItemGeolocationRelationshipsCreatorDataMember5);
            }
        }
    }
}
#pragma warning restore CS0618
