// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Persona.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Persona.OpenApiClient.Models.ListItemCountryRelationshipsCreatorDataOneOf2"/>, <see cref="global::Soenneker.Persona.OpenApiClient.Models.ListItemCountryRelationshipsCreatorDataOneOf3"/>, <see cref="global::Soenneker.Persona.OpenApiClient.Models.ListItemCountryRelationshipsCreatorDataOneOf4"/>, <see cref="global::Soenneker.Persona.OpenApiClient.Models.ListItemCountryRelationshipsCreatorDataOneOf5"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ListItemCountryRelationshipsCreatorData : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Persona.OpenApiClient.Models.ListItemCountryRelationshipsCreatorDataOneOf2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Persona.OpenApiClient.Models.ListItemCountryRelationshipsCreatorDataOneOf2? ListItemCountryRelationshipsCreatorDataOneOf2 { get; set; }
#nullable restore
#else
        public global::Soenneker.Persona.OpenApiClient.Models.ListItemCountryRelationshipsCreatorDataOneOf2 ListItemCountryRelationshipsCreatorDataOneOf2 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Persona.OpenApiClient.Models.ListItemCountryRelationshipsCreatorDataOneOf3"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Persona.OpenApiClient.Models.ListItemCountryRelationshipsCreatorDataOneOf3? ListItemCountryRelationshipsCreatorDataOneOf3 { get; set; }
#nullable restore
#else
        public global::Soenneker.Persona.OpenApiClient.Models.ListItemCountryRelationshipsCreatorDataOneOf3 ListItemCountryRelationshipsCreatorDataOneOf3 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Persona.OpenApiClient.Models.ListItemCountryRelationshipsCreatorDataOneOf4"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Persona.OpenApiClient.Models.ListItemCountryRelationshipsCreatorDataOneOf4? ListItemCountryRelationshipsCreatorDataOneOf4 { get; set; }
#nullable restore
#else
        public global::Soenneker.Persona.OpenApiClient.Models.ListItemCountryRelationshipsCreatorDataOneOf4 ListItemCountryRelationshipsCreatorDataOneOf4 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Persona.OpenApiClient.Models.ListItemCountryRelationshipsCreatorDataOneOf5"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Persona.OpenApiClient.Models.ListItemCountryRelationshipsCreatorDataOneOf5? ListItemCountryRelationshipsCreatorDataOneOf5 { get; set; }
#nullable restore
#else
        public global::Soenneker.Persona.OpenApiClient.Models.ListItemCountryRelationshipsCreatorDataOneOf5 ListItemCountryRelationshipsCreatorDataOneOf5 { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Persona.OpenApiClient.Models.ListItemCountryRelationshipsCreatorData"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Persona.OpenApiClient.Models.ListItemCountryRelationshipsCreatorData CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            var result = new global::Soenneker.Persona.OpenApiClient.Models.ListItemCountryRelationshipsCreatorData();
            if("ListItemCountryRelationshipsCreatorDataOneOf2".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ListItemCountryRelationshipsCreatorDataOneOf2 = new global::Soenneker.Persona.OpenApiClient.Models.ListItemCountryRelationshipsCreatorDataOneOf2();
            }
            else if("ListItemCountryRelationshipsCreatorDataOneOf3".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ListItemCountryRelationshipsCreatorDataOneOf3 = new global::Soenneker.Persona.OpenApiClient.Models.ListItemCountryRelationshipsCreatorDataOneOf3();
            }
            else if("ListItemCountryRelationshipsCreatorDataOneOf4".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ListItemCountryRelationshipsCreatorDataOneOf4 = new global::Soenneker.Persona.OpenApiClient.Models.ListItemCountryRelationshipsCreatorDataOneOf4();
            }
            else if("ListItemCountryRelationshipsCreatorDataOneOf5".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ListItemCountryRelationshipsCreatorDataOneOf5 = new global::Soenneker.Persona.OpenApiClient.Models.ListItemCountryRelationshipsCreatorDataOneOf5();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(ListItemCountryRelationshipsCreatorDataOneOf2 != null)
            {
                return ListItemCountryRelationshipsCreatorDataOneOf2.GetFieldDeserializers();
            }
            else if(ListItemCountryRelationshipsCreatorDataOneOf3 != null)
            {
                return ListItemCountryRelationshipsCreatorDataOneOf3.GetFieldDeserializers();
            }
            else if(ListItemCountryRelationshipsCreatorDataOneOf4 != null)
            {
                return ListItemCountryRelationshipsCreatorDataOneOf4.GetFieldDeserializers();
            }
            else if(ListItemCountryRelationshipsCreatorDataOneOf5 != null)
            {
                return ListItemCountryRelationshipsCreatorDataOneOf5.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(ListItemCountryRelationshipsCreatorDataOneOf2 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Persona.OpenApiClient.Models.ListItemCountryRelationshipsCreatorDataOneOf2>(null, ListItemCountryRelationshipsCreatorDataOneOf2);
            }
            else if(ListItemCountryRelationshipsCreatorDataOneOf3 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Persona.OpenApiClient.Models.ListItemCountryRelationshipsCreatorDataOneOf3>(null, ListItemCountryRelationshipsCreatorDataOneOf3);
            }
            else if(ListItemCountryRelationshipsCreatorDataOneOf4 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Persona.OpenApiClient.Models.ListItemCountryRelationshipsCreatorDataOneOf4>(null, ListItemCountryRelationshipsCreatorDataOneOf4);
            }
            else if(ListItemCountryRelationshipsCreatorDataOneOf5 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Persona.OpenApiClient.Models.ListItemCountryRelationshipsCreatorDataOneOf5>(null, ListItemCountryRelationshipsCreatorDataOneOf5);
            }
        }
    }
}
#pragma warning restore CS0618
