// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Persona.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Persona.OpenApiClient.Models.ListItemEmailAddressRelationshipsCreatorDataMember1"/>, <see cref="global::Soenneker.Persona.OpenApiClient.Models.ListItemEmailAddressRelationshipsCreatorDataOneOf2"/>, <see cref="global::Soenneker.Persona.OpenApiClient.Models.ListItemEmailAddressRelationshipsCreatorDataOneOf3"/>, <see cref="global::Soenneker.Persona.OpenApiClient.Models.ListItemEmailAddressRelationshipsCreatorDataOneOf4"/>, <see cref="global::Soenneker.Persona.OpenApiClient.Models.ListItemEmailAddressRelationshipsCreatorDataOneOf5"/>, <see cref="global::Soenneker.Persona.OpenApiClient.Models.ListItemEmailAddressRelationshipsCreatorDataOneOf6"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ListItemEmailAddressRelationshipsCreatorData : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Persona.OpenApiClient.Models.ListItemEmailAddressRelationshipsCreatorDataMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Persona.OpenApiClient.Models.ListItemEmailAddressRelationshipsCreatorDataMember1? ListItemEmailAddressRelationshipsCreatorDataMember1 { get; set; }
#nullable restore
#else
        public global::Soenneker.Persona.OpenApiClient.Models.ListItemEmailAddressRelationshipsCreatorDataMember1 ListItemEmailAddressRelationshipsCreatorDataMember1 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Persona.OpenApiClient.Models.ListItemEmailAddressRelationshipsCreatorDataOneOf2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Persona.OpenApiClient.Models.ListItemEmailAddressRelationshipsCreatorDataOneOf2? ListItemEmailAddressRelationshipsCreatorDataOneOf2 { get; set; }
#nullable restore
#else
        public global::Soenneker.Persona.OpenApiClient.Models.ListItemEmailAddressRelationshipsCreatorDataOneOf2 ListItemEmailAddressRelationshipsCreatorDataOneOf2 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Persona.OpenApiClient.Models.ListItemEmailAddressRelationshipsCreatorDataOneOf3"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Persona.OpenApiClient.Models.ListItemEmailAddressRelationshipsCreatorDataOneOf3? ListItemEmailAddressRelationshipsCreatorDataOneOf3 { get; set; }
#nullable restore
#else
        public global::Soenneker.Persona.OpenApiClient.Models.ListItemEmailAddressRelationshipsCreatorDataOneOf3 ListItemEmailAddressRelationshipsCreatorDataOneOf3 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Persona.OpenApiClient.Models.ListItemEmailAddressRelationshipsCreatorDataOneOf4"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Persona.OpenApiClient.Models.ListItemEmailAddressRelationshipsCreatorDataOneOf4? ListItemEmailAddressRelationshipsCreatorDataOneOf4 { get; set; }
#nullable restore
#else
        public global::Soenneker.Persona.OpenApiClient.Models.ListItemEmailAddressRelationshipsCreatorDataOneOf4 ListItemEmailAddressRelationshipsCreatorDataOneOf4 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Persona.OpenApiClient.Models.ListItemEmailAddressRelationshipsCreatorDataOneOf5"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Persona.OpenApiClient.Models.ListItemEmailAddressRelationshipsCreatorDataOneOf5? ListItemEmailAddressRelationshipsCreatorDataOneOf5 { get; set; }
#nullable restore
#else
        public global::Soenneker.Persona.OpenApiClient.Models.ListItemEmailAddressRelationshipsCreatorDataOneOf5 ListItemEmailAddressRelationshipsCreatorDataOneOf5 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Persona.OpenApiClient.Models.ListItemEmailAddressRelationshipsCreatorDataOneOf6"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Persona.OpenApiClient.Models.ListItemEmailAddressRelationshipsCreatorDataOneOf6? ListItemEmailAddressRelationshipsCreatorDataOneOf6 { get; set; }
#nullable restore
#else
        public global::Soenneker.Persona.OpenApiClient.Models.ListItemEmailAddressRelationshipsCreatorDataOneOf6 ListItemEmailAddressRelationshipsCreatorDataOneOf6 { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Persona.OpenApiClient.Models.ListItemEmailAddressRelationshipsCreatorData"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Persona.OpenApiClient.Models.ListItemEmailAddressRelationshipsCreatorData CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            var result = new global::Soenneker.Persona.OpenApiClient.Models.ListItemEmailAddressRelationshipsCreatorData();
            if("ListItemEmailAddressRelationshipsCreatorDataOneOf2".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ListItemEmailAddressRelationshipsCreatorDataOneOf2 = new global::Soenneker.Persona.OpenApiClient.Models.ListItemEmailAddressRelationshipsCreatorDataOneOf2();
            }
            else if("ListItemEmailAddressRelationshipsCreatorDataOneOf3".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ListItemEmailAddressRelationshipsCreatorDataOneOf3 = new global::Soenneker.Persona.OpenApiClient.Models.ListItemEmailAddressRelationshipsCreatorDataOneOf3();
            }
            else if("ListItemEmailAddressRelationshipsCreatorDataOneOf4".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ListItemEmailAddressRelationshipsCreatorDataOneOf4 = new global::Soenneker.Persona.OpenApiClient.Models.ListItemEmailAddressRelationshipsCreatorDataOneOf4();
            }
            else if("ListItemEmailAddressRelationshipsCreatorDataOneOf5".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ListItemEmailAddressRelationshipsCreatorDataOneOf5 = new global::Soenneker.Persona.OpenApiClient.Models.ListItemEmailAddressRelationshipsCreatorDataOneOf5();
            }
            else if("ListItemEmailAddressRelationshipsCreatorDataOneOf6".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ListItemEmailAddressRelationshipsCreatorDataOneOf6 = new global::Soenneker.Persona.OpenApiClient.Models.ListItemEmailAddressRelationshipsCreatorDataOneOf6();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(ListItemEmailAddressRelationshipsCreatorDataMember1 != null)
            {
                return ListItemEmailAddressRelationshipsCreatorDataMember1.GetFieldDeserializers();
            }
            else if(ListItemEmailAddressRelationshipsCreatorDataOneOf2 != null)
            {
                return ListItemEmailAddressRelationshipsCreatorDataOneOf2.GetFieldDeserializers();
            }
            else if(ListItemEmailAddressRelationshipsCreatorDataOneOf3 != null)
            {
                return ListItemEmailAddressRelationshipsCreatorDataOneOf3.GetFieldDeserializers();
            }
            else if(ListItemEmailAddressRelationshipsCreatorDataOneOf4 != null)
            {
                return ListItemEmailAddressRelationshipsCreatorDataOneOf4.GetFieldDeserializers();
            }
            else if(ListItemEmailAddressRelationshipsCreatorDataOneOf5 != null)
            {
                return ListItemEmailAddressRelationshipsCreatorDataOneOf5.GetFieldDeserializers();
            }
            else if(ListItemEmailAddressRelationshipsCreatorDataOneOf6 != null)
            {
                return ListItemEmailAddressRelationshipsCreatorDataOneOf6.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(ListItemEmailAddressRelationshipsCreatorDataMember1 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Persona.OpenApiClient.Models.ListItemEmailAddressRelationshipsCreatorDataMember1>(null, ListItemEmailAddressRelationshipsCreatorDataMember1);
            }
            else if(ListItemEmailAddressRelationshipsCreatorDataOneOf2 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Persona.OpenApiClient.Models.ListItemEmailAddressRelationshipsCreatorDataOneOf2>(null, ListItemEmailAddressRelationshipsCreatorDataOneOf2);
            }
            else if(ListItemEmailAddressRelationshipsCreatorDataOneOf3 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Persona.OpenApiClient.Models.ListItemEmailAddressRelationshipsCreatorDataOneOf3>(null, ListItemEmailAddressRelationshipsCreatorDataOneOf3);
            }
            else if(ListItemEmailAddressRelationshipsCreatorDataOneOf4 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Persona.OpenApiClient.Models.ListItemEmailAddressRelationshipsCreatorDataOneOf4>(null, ListItemEmailAddressRelationshipsCreatorDataOneOf4);
            }
            else if(ListItemEmailAddressRelationshipsCreatorDataOneOf5 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Persona.OpenApiClient.Models.ListItemEmailAddressRelationshipsCreatorDataOneOf5>(null, ListItemEmailAddressRelationshipsCreatorDataOneOf5);
            }
            else if(ListItemEmailAddressRelationshipsCreatorDataOneOf6 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Persona.OpenApiClient.Models.ListItemEmailAddressRelationshipsCreatorDataOneOf6>(null, ListItemEmailAddressRelationshipsCreatorDataOneOf6);
            }
        }
    }
}
#pragma warning restore CS0618
