// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Persona.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Persona.OpenApiClient.Models.Account"/>, <see cref="global::Soenneker.Persona.OpenApiClient.Models.CaseType"/>, <see cref="global::Soenneker.Persona.OpenApiClient.Models.Inquiry"/>, <see cref="global::Soenneker.Persona.OpenApiClient.Models.ReportTemplateAddressLookup"/>, <see cref="global::Soenneker.Persona.OpenApiClient.Models.ReportTemplateAdverseMedia"/>, <see cref="global::Soenneker.Persona.OpenApiClient.Models.ReportTemplateBusinessAdverseMedia"/>, <see cref="global::Soenneker.Persona.OpenApiClient.Models.ReportTemplateBusinessAssociatedPersons"/>, <see cref="global::Soenneker.Persona.OpenApiClient.Models.ReportTemplateBusinessLookup"/>, <see cref="global::Soenneker.Persona.OpenApiClient.Models.ReportTemplateBusinessRegistrationsLookup"/>, <see cref="global::Soenneker.Persona.OpenApiClient.Models.ReportTemplateBusinessWatchlist"/>, <see cref="global::Soenneker.Persona.OpenApiClient.Models.ReportTemplateCryptoAddressWatchlist"/>, <see cref="global::Soenneker.Persona.OpenApiClient.Models.ReportTemplateEmailAddress"/>, <see cref="global::Soenneker.Persona.OpenApiClient.Models.ReportTemplatePhoneRisk"/>, <see cref="global::Soenneker.Persona.OpenApiClient.Models.ReportTemplatePoliticallyExposedPerson"/>, <see cref="global::Soenneker.Persona.OpenApiClient.Models.ReportTemplateProfile"/>, <see cref="global::Soenneker.Persona.OpenApiClient.Models.ReportTemplateSentilinkScores"/>, <see cref="global::Soenneker.Persona.OpenApiClient.Models.ReportTemplateSocialMedia"/>, <see cref="global::Soenneker.Persona.OpenApiClient.Models.ReportTemplateSynthetic"/>, <see cref="global::Soenneker.Persona.OpenApiClient.Models.ReportTemplateWatchlist"/>, <see cref="global::Soenneker.Persona.OpenApiClient.Models.Transaction"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ReportsIncludedObjectsItem : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Persona.OpenApiClient.Models.Account"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Persona.OpenApiClient.Models.Account? Account { get; set; }
#nullable restore
#else
        public global::Soenneker.Persona.OpenApiClient.Models.Account Account { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Persona.OpenApiClient.Models.CaseType"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Persona.OpenApiClient.Models.CaseType? CaseType { get; set; }
#nullable restore
#else
        public global::Soenneker.Persona.OpenApiClient.Models.CaseType CaseType { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Persona.OpenApiClient.Models.Inquiry"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Persona.OpenApiClient.Models.Inquiry? Inquiry { get; set; }
#nullable restore
#else
        public global::Soenneker.Persona.OpenApiClient.Models.Inquiry Inquiry { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Persona.OpenApiClient.Models.ReportTemplateAddressLookup"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Persona.OpenApiClient.Models.ReportTemplateAddressLookup? ReportTemplateAddressLookup { get; set; }
#nullable restore
#else
        public global::Soenneker.Persona.OpenApiClient.Models.ReportTemplateAddressLookup ReportTemplateAddressLookup { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Persona.OpenApiClient.Models.ReportTemplateAdverseMedia"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Persona.OpenApiClient.Models.ReportTemplateAdverseMedia? ReportTemplateAdverseMedia { get; set; }
#nullable restore
#else
        public global::Soenneker.Persona.OpenApiClient.Models.ReportTemplateAdverseMedia ReportTemplateAdverseMedia { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Persona.OpenApiClient.Models.ReportTemplateBusinessAdverseMedia"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Persona.OpenApiClient.Models.ReportTemplateBusinessAdverseMedia? ReportTemplateBusinessAdverseMedia { get; set; }
#nullable restore
#else
        public global::Soenneker.Persona.OpenApiClient.Models.ReportTemplateBusinessAdverseMedia ReportTemplateBusinessAdverseMedia { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Persona.OpenApiClient.Models.ReportTemplateBusinessAssociatedPersons"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Persona.OpenApiClient.Models.ReportTemplateBusinessAssociatedPersons? ReportTemplateBusinessAssociatedPersons { get; set; }
#nullable restore
#else
        public global::Soenneker.Persona.OpenApiClient.Models.ReportTemplateBusinessAssociatedPersons ReportTemplateBusinessAssociatedPersons { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Persona.OpenApiClient.Models.ReportTemplateBusinessLookup"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Persona.OpenApiClient.Models.ReportTemplateBusinessLookup? ReportTemplateBusinessLookup { get; set; }
#nullable restore
#else
        public global::Soenneker.Persona.OpenApiClient.Models.ReportTemplateBusinessLookup ReportTemplateBusinessLookup { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Persona.OpenApiClient.Models.ReportTemplateBusinessRegistrationsLookup"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Persona.OpenApiClient.Models.ReportTemplateBusinessRegistrationsLookup? ReportTemplateBusinessRegistrationsLookup { get; set; }
#nullable restore
#else
        public global::Soenneker.Persona.OpenApiClient.Models.ReportTemplateBusinessRegistrationsLookup ReportTemplateBusinessRegistrationsLookup { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Persona.OpenApiClient.Models.ReportTemplateBusinessWatchlist"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Persona.OpenApiClient.Models.ReportTemplateBusinessWatchlist? ReportTemplateBusinessWatchlist { get; set; }
#nullable restore
#else
        public global::Soenneker.Persona.OpenApiClient.Models.ReportTemplateBusinessWatchlist ReportTemplateBusinessWatchlist { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Persona.OpenApiClient.Models.ReportTemplateCryptoAddressWatchlist"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Persona.OpenApiClient.Models.ReportTemplateCryptoAddressWatchlist? ReportTemplateCryptoAddressWatchlist { get; set; }
#nullable restore
#else
        public global::Soenneker.Persona.OpenApiClient.Models.ReportTemplateCryptoAddressWatchlist ReportTemplateCryptoAddressWatchlist { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Persona.OpenApiClient.Models.ReportTemplateEmailAddress"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Persona.OpenApiClient.Models.ReportTemplateEmailAddress? ReportTemplateEmailAddress { get; set; }
#nullable restore
#else
        public global::Soenneker.Persona.OpenApiClient.Models.ReportTemplateEmailAddress ReportTemplateEmailAddress { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Persona.OpenApiClient.Models.ReportTemplatePhoneRisk"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Persona.OpenApiClient.Models.ReportTemplatePhoneRisk? ReportTemplatePhoneRisk { get; set; }
#nullable restore
#else
        public global::Soenneker.Persona.OpenApiClient.Models.ReportTemplatePhoneRisk ReportTemplatePhoneRisk { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Persona.OpenApiClient.Models.ReportTemplatePoliticallyExposedPerson"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Persona.OpenApiClient.Models.ReportTemplatePoliticallyExposedPerson? ReportTemplatePoliticallyExposedPerson { get; set; }
#nullable restore
#else
        public global::Soenneker.Persona.OpenApiClient.Models.ReportTemplatePoliticallyExposedPerson ReportTemplatePoliticallyExposedPerson { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Persona.OpenApiClient.Models.ReportTemplateProfile"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Persona.OpenApiClient.Models.ReportTemplateProfile? ReportTemplateProfile { get; set; }
#nullable restore
#else
        public global::Soenneker.Persona.OpenApiClient.Models.ReportTemplateProfile ReportTemplateProfile { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Persona.OpenApiClient.Models.ReportTemplateSentilinkScores"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Persona.OpenApiClient.Models.ReportTemplateSentilinkScores? ReportTemplateSentilinkScores { get; set; }
#nullable restore
#else
        public global::Soenneker.Persona.OpenApiClient.Models.ReportTemplateSentilinkScores ReportTemplateSentilinkScores { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Persona.OpenApiClient.Models.ReportTemplateSocialMedia"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Persona.OpenApiClient.Models.ReportTemplateSocialMedia? ReportTemplateSocialMedia { get; set; }
#nullable restore
#else
        public global::Soenneker.Persona.OpenApiClient.Models.ReportTemplateSocialMedia ReportTemplateSocialMedia { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Persona.OpenApiClient.Models.ReportTemplateSynthetic"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Persona.OpenApiClient.Models.ReportTemplateSynthetic? ReportTemplateSynthetic { get; set; }
#nullable restore
#else
        public global::Soenneker.Persona.OpenApiClient.Models.ReportTemplateSynthetic ReportTemplateSynthetic { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Persona.OpenApiClient.Models.ReportTemplateWatchlist"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Persona.OpenApiClient.Models.ReportTemplateWatchlist? ReportTemplateWatchlist { get; set; }
#nullable restore
#else
        public global::Soenneker.Persona.OpenApiClient.Models.ReportTemplateWatchlist ReportTemplateWatchlist { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Persona.OpenApiClient.Models.Transaction"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Persona.OpenApiClient.Models.Transaction? Transaction { get; set; }
#nullable restore
#else
        public global::Soenneker.Persona.OpenApiClient.Models.Transaction Transaction { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Persona.OpenApiClient.Models.ReportsIncludedObjectsItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Persona.OpenApiClient.Models.ReportsIncludedObjectsItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            var result = new global::Soenneker.Persona.OpenApiClient.Models.ReportsIncludedObjectsItem();
            if("account".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.Account = new global::Soenneker.Persona.OpenApiClient.Models.Account();
            }
            else if("case".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.CaseType = new global::Soenneker.Persona.OpenApiClient.Models.CaseType();
            }
            else if("inquiry".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.Inquiry = new global::Soenneker.Persona.OpenApiClient.Models.Inquiry();
            }
            else if("report-template/address-lookup".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ReportTemplateAddressLookup = new global::Soenneker.Persona.OpenApiClient.Models.ReportTemplateAddressLookup();
            }
            else if("report-template/adverse-media".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ReportTemplateAdverseMedia = new global::Soenneker.Persona.OpenApiClient.Models.ReportTemplateAdverseMedia();
            }
            else if("report-template/business-adverse-media".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ReportTemplateBusinessAdverseMedia = new global::Soenneker.Persona.OpenApiClient.Models.ReportTemplateBusinessAdverseMedia();
            }
            else if("report-template/business-associated-persons".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ReportTemplateBusinessAssociatedPersons = new global::Soenneker.Persona.OpenApiClient.Models.ReportTemplateBusinessAssociatedPersons();
            }
            else if("report-template/business-lookup".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ReportTemplateBusinessLookup = new global::Soenneker.Persona.OpenApiClient.Models.ReportTemplateBusinessLookup();
            }
            else if("report-template/business-registrations-lookup".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ReportTemplateBusinessRegistrationsLookup = new global::Soenneker.Persona.OpenApiClient.Models.ReportTemplateBusinessRegistrationsLookup();
            }
            else if("report-template/business-watchlist".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ReportTemplateBusinessWatchlist = new global::Soenneker.Persona.OpenApiClient.Models.ReportTemplateBusinessWatchlist();
            }
            else if("report-template/crypto-address-watchlist".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ReportTemplateCryptoAddressWatchlist = new global::Soenneker.Persona.OpenApiClient.Models.ReportTemplateCryptoAddressWatchlist();
            }
            else if("report-template/email-address".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ReportTemplateEmailAddress = new global::Soenneker.Persona.OpenApiClient.Models.ReportTemplateEmailAddress();
            }
            else if("report-template/phone-number".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ReportTemplatePhoneRisk = new global::Soenneker.Persona.OpenApiClient.Models.ReportTemplatePhoneRisk();
            }
            else if("report-template/politically-exposed-person".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ReportTemplatePoliticallyExposedPerson = new global::Soenneker.Persona.OpenApiClient.Models.ReportTemplatePoliticallyExposedPerson();
            }
            else if("report-template/profile".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ReportTemplateProfile = new global::Soenneker.Persona.OpenApiClient.Models.ReportTemplateProfile();
            }
            else if("report-template/integration/sentilink-scores".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ReportTemplateSentilinkScores = new global::Soenneker.Persona.OpenApiClient.Models.ReportTemplateSentilinkScores();
            }
            else if("report-template/social-media".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ReportTemplateSocialMedia = new global::Soenneker.Persona.OpenApiClient.Models.ReportTemplateSocialMedia();
            }
            else if("report-template/synthetic".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ReportTemplateSynthetic = new global::Soenneker.Persona.OpenApiClient.Models.ReportTemplateSynthetic();
            }
            else if("report-template/watchlist".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ReportTemplateWatchlist = new global::Soenneker.Persona.OpenApiClient.Models.ReportTemplateWatchlist();
            }
            else if("transaction".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.Transaction = new global::Soenneker.Persona.OpenApiClient.Models.Transaction();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(Account != null)
            {
                return Account.GetFieldDeserializers();
            }
            else if(CaseType != null)
            {
                return CaseType.GetFieldDeserializers();
            }
            else if(Inquiry != null)
            {
                return Inquiry.GetFieldDeserializers();
            }
            else if(ReportTemplateAddressLookup != null)
            {
                return ReportTemplateAddressLookup.GetFieldDeserializers();
            }
            else if(ReportTemplateAdverseMedia != null)
            {
                return ReportTemplateAdverseMedia.GetFieldDeserializers();
            }
            else if(ReportTemplateBusinessAdverseMedia != null)
            {
                return ReportTemplateBusinessAdverseMedia.GetFieldDeserializers();
            }
            else if(ReportTemplateBusinessAssociatedPersons != null)
            {
                return ReportTemplateBusinessAssociatedPersons.GetFieldDeserializers();
            }
            else if(ReportTemplateBusinessLookup != null)
            {
                return ReportTemplateBusinessLookup.GetFieldDeserializers();
            }
            else if(ReportTemplateBusinessRegistrationsLookup != null)
            {
                return ReportTemplateBusinessRegistrationsLookup.GetFieldDeserializers();
            }
            else if(ReportTemplateBusinessWatchlist != null)
            {
                return ReportTemplateBusinessWatchlist.GetFieldDeserializers();
            }
            else if(ReportTemplateCryptoAddressWatchlist != null)
            {
                return ReportTemplateCryptoAddressWatchlist.GetFieldDeserializers();
            }
            else if(ReportTemplateEmailAddress != null)
            {
                return ReportTemplateEmailAddress.GetFieldDeserializers();
            }
            else if(ReportTemplatePhoneRisk != null)
            {
                return ReportTemplatePhoneRisk.GetFieldDeserializers();
            }
            else if(ReportTemplatePoliticallyExposedPerson != null)
            {
                return ReportTemplatePoliticallyExposedPerson.GetFieldDeserializers();
            }
            else if(ReportTemplateProfile != null)
            {
                return ReportTemplateProfile.GetFieldDeserializers();
            }
            else if(ReportTemplateSentilinkScores != null)
            {
                return ReportTemplateSentilinkScores.GetFieldDeserializers();
            }
            else if(ReportTemplateSocialMedia != null)
            {
                return ReportTemplateSocialMedia.GetFieldDeserializers();
            }
            else if(ReportTemplateSynthetic != null)
            {
                return ReportTemplateSynthetic.GetFieldDeserializers();
            }
            else if(ReportTemplateWatchlist != null)
            {
                return ReportTemplateWatchlist.GetFieldDeserializers();
            }
            else if(Transaction != null)
            {
                return Transaction.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(Account != null)
            {
                writer.WriteObjectValue<global::Soenneker.Persona.OpenApiClient.Models.Account>(null, Account);
            }
            else if(CaseType != null)
            {
                writer.WriteObjectValue<global::Soenneker.Persona.OpenApiClient.Models.CaseType>(null, CaseType);
            }
            else if(Inquiry != null)
            {
                writer.WriteObjectValue<global::Soenneker.Persona.OpenApiClient.Models.Inquiry>(null, Inquiry);
            }
            else if(ReportTemplateAddressLookup != null)
            {
                writer.WriteObjectValue<global::Soenneker.Persona.OpenApiClient.Models.ReportTemplateAddressLookup>(null, ReportTemplateAddressLookup);
            }
            else if(ReportTemplateAdverseMedia != null)
            {
                writer.WriteObjectValue<global::Soenneker.Persona.OpenApiClient.Models.ReportTemplateAdverseMedia>(null, ReportTemplateAdverseMedia);
            }
            else if(ReportTemplateBusinessAdverseMedia != null)
            {
                writer.WriteObjectValue<global::Soenneker.Persona.OpenApiClient.Models.ReportTemplateBusinessAdverseMedia>(null, ReportTemplateBusinessAdverseMedia);
            }
            else if(ReportTemplateBusinessAssociatedPersons != null)
            {
                writer.WriteObjectValue<global::Soenneker.Persona.OpenApiClient.Models.ReportTemplateBusinessAssociatedPersons>(null, ReportTemplateBusinessAssociatedPersons);
            }
            else if(ReportTemplateBusinessLookup != null)
            {
                writer.WriteObjectValue<global::Soenneker.Persona.OpenApiClient.Models.ReportTemplateBusinessLookup>(null, ReportTemplateBusinessLookup);
            }
            else if(ReportTemplateBusinessRegistrationsLookup != null)
            {
                writer.WriteObjectValue<global::Soenneker.Persona.OpenApiClient.Models.ReportTemplateBusinessRegistrationsLookup>(null, ReportTemplateBusinessRegistrationsLookup);
            }
            else if(ReportTemplateBusinessWatchlist != null)
            {
                writer.WriteObjectValue<global::Soenneker.Persona.OpenApiClient.Models.ReportTemplateBusinessWatchlist>(null, ReportTemplateBusinessWatchlist);
            }
            else if(ReportTemplateCryptoAddressWatchlist != null)
            {
                writer.WriteObjectValue<global::Soenneker.Persona.OpenApiClient.Models.ReportTemplateCryptoAddressWatchlist>(null, ReportTemplateCryptoAddressWatchlist);
            }
            else if(ReportTemplateEmailAddress != null)
            {
                writer.WriteObjectValue<global::Soenneker.Persona.OpenApiClient.Models.ReportTemplateEmailAddress>(null, ReportTemplateEmailAddress);
            }
            else if(ReportTemplatePhoneRisk != null)
            {
                writer.WriteObjectValue<global::Soenneker.Persona.OpenApiClient.Models.ReportTemplatePhoneRisk>(null, ReportTemplatePhoneRisk);
            }
            else if(ReportTemplatePoliticallyExposedPerson != null)
            {
                writer.WriteObjectValue<global::Soenneker.Persona.OpenApiClient.Models.ReportTemplatePoliticallyExposedPerson>(null, ReportTemplatePoliticallyExposedPerson);
            }
            else if(ReportTemplateProfile != null)
            {
                writer.WriteObjectValue<global::Soenneker.Persona.OpenApiClient.Models.ReportTemplateProfile>(null, ReportTemplateProfile);
            }
            else if(ReportTemplateSentilinkScores != null)
            {
                writer.WriteObjectValue<global::Soenneker.Persona.OpenApiClient.Models.ReportTemplateSentilinkScores>(null, ReportTemplateSentilinkScores);
            }
            else if(ReportTemplateSocialMedia != null)
            {
                writer.WriteObjectValue<global::Soenneker.Persona.OpenApiClient.Models.ReportTemplateSocialMedia>(null, ReportTemplateSocialMedia);
            }
            else if(ReportTemplateSynthetic != null)
            {
                writer.WriteObjectValue<global::Soenneker.Persona.OpenApiClient.Models.ReportTemplateSynthetic>(null, ReportTemplateSynthetic);
            }
            else if(ReportTemplateWatchlist != null)
            {
                writer.WriteObjectValue<global::Soenneker.Persona.OpenApiClient.Models.ReportTemplateWatchlist>(null, ReportTemplateWatchlist);
            }
            else if(Transaction != null)
            {
                writer.WriteObjectValue<global::Soenneker.Persona.OpenApiClient.Models.Transaction>(null, Transaction);
            }
        }
    }
}
#pragma warning restore CS0618
