// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Persona.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ReportAdverseMediaAttributes_relatedSources : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The akas property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Akas { get; set; }
#nullable restore
#else
        public List<string> Akas { get; set; }
#endif
        /// <summary>The birthdates property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Birthdates { get; set; }
#nullable restore
#else
        public List<string> Birthdates { get; set; }
#endif
        /// <summary>The entityId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EntityId { get; set; }
#nullable restore
#else
        public string EntityId { get; set; }
#endif
        /// <summary>The matchTypes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? MatchTypes { get; set; }
#nullable restore
#else
        public List<string> MatchTypes { get; set; }
#endif
        /// <summary>The media property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Persona.OpenApiClient.Models.ReportAdverseMediaAttributes_relatedSources_media>? Media { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Persona.OpenApiClient.Models.ReportAdverseMediaAttributes_relatedSources_media> Media { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The sources property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Persona.OpenApiClient.Models.ReportAdverseMediaAttributes_relatedSources_sources>? Sources { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Persona.OpenApiClient.Models.ReportAdverseMediaAttributes_relatedSources_sources> Sources { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Persona.OpenApiClient.Models.ReportAdverseMediaAttributes_relatedSources"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Persona.OpenApiClient.Models.ReportAdverseMediaAttributes_relatedSources CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Persona.OpenApiClient.Models.ReportAdverseMediaAttributes_relatedSources();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "akas", n => { Akas = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "birthdates", n => { Birthdates = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "entity-id", n => { EntityId = n.GetStringValue(); } },
                { "match-types", n => { MatchTypes = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "media", n => { Media = n.GetCollectionOfObjectValues<global::Soenneker.Persona.OpenApiClient.Models.ReportAdverseMediaAttributes_relatedSources_media>(global::Soenneker.Persona.OpenApiClient.Models.ReportAdverseMediaAttributes_relatedSources_media.CreateFromDiscriminatorValue)?.AsList(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "sources", n => { Sources = n.GetCollectionOfObjectValues<global::Soenneker.Persona.OpenApiClient.Models.ReportAdverseMediaAttributes_relatedSources_sources>(global::Soenneker.Persona.OpenApiClient.Models.ReportAdverseMediaAttributes_relatedSources_sources.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<string>("akas", Akas);
            writer.WriteCollectionOfPrimitiveValues<string>("birthdates", Birthdates);
            writer.WriteStringValue("entity-id", EntityId);
            writer.WriteCollectionOfPrimitiveValues<string>("match-types", MatchTypes);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Persona.OpenApiClient.Models.ReportAdverseMediaAttributes_relatedSources_media>("media", Media);
            writer.WriteStringValue("name", Name);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Persona.OpenApiClient.Models.ReportAdverseMediaAttributes_relatedSources_sources>("sources", Sources);
        }
    }
}
#pragma warning restore CS0618
