// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Persona.OpenApiClient.Models
{
    /// <summary>
    /// Other Persona objects related to the report
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Report_shared_relationships : IParsable
    {
        /// <summary>The account linked to the report</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Persona.OpenApiClient.Models.Report_shared_relationships_account? Account { get; set; }
#nullable restore
#else
        public global::Soenneker.Persona.OpenApiClient.Models.Report_shared_relationships_account Account { get; set; }
#endif
        /// <summary>The inquiry linked to the report</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Persona.OpenApiClient.Models.Report_shared_relationships_inquiry? Inquiry { get; set; }
#nullable restore
#else
        public global::Soenneker.Persona.OpenApiClient.Models.Report_shared_relationships_inquiry Inquiry { get; set; }
#endif
        /// <summary>The report template used to create this report</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Persona.OpenApiClient.Models.Report_shared_relationships_reportTemplate? ReportTemplate { get; set; }
#nullable restore
#else
        public global::Soenneker.Persona.OpenApiClient.Models.Report_shared_relationships_reportTemplate ReportTemplate { get; set; }
#endif
        /// <summary>The transaction linked to the report</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Persona.OpenApiClient.Models.Report_shared_relationships_transaction? Transaction { get; set; }
#nullable restore
#else
        public global::Soenneker.Persona.OpenApiClient.Models.Report_shared_relationships_transaction Transaction { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Persona.OpenApiClient.Models.Report_shared_relationships"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Persona.OpenApiClient.Models.Report_shared_relationships CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Persona.OpenApiClient.Models.Report_shared_relationships();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "account", n => { Account = n.GetObjectValue<global::Soenneker.Persona.OpenApiClient.Models.Report_shared_relationships_account>(global::Soenneker.Persona.OpenApiClient.Models.Report_shared_relationships_account.CreateFromDiscriminatorValue); } },
                { "inquiry", n => { Inquiry = n.GetObjectValue<global::Soenneker.Persona.OpenApiClient.Models.Report_shared_relationships_inquiry>(global::Soenneker.Persona.OpenApiClient.Models.Report_shared_relationships_inquiry.CreateFromDiscriminatorValue); } },
                { "report-template", n => { ReportTemplate = n.GetObjectValue<global::Soenneker.Persona.OpenApiClient.Models.Report_shared_relationships_reportTemplate>(global::Soenneker.Persona.OpenApiClient.Models.Report_shared_relationships_reportTemplate.CreateFromDiscriminatorValue); } },
                { "transaction", n => { Transaction = n.GetObjectValue<global::Soenneker.Persona.OpenApiClient.Models.Report_shared_relationships_transaction>(global::Soenneker.Persona.OpenApiClient.Models.Report_shared_relationships_transaction.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Persona.OpenApiClient.Models.Report_shared_relationships_account>("account", Account);
            writer.WriteObjectValue<global::Soenneker.Persona.OpenApiClient.Models.Report_shared_relationships_inquiry>("inquiry", Inquiry);
            writer.WriteObjectValue<global::Soenneker.Persona.OpenApiClient.Models.Report_shared_relationships_reportTemplate>("report-template", ReportTemplate);
            writer.WriteObjectValue<global::Soenneker.Persona.OpenApiClient.Models.Report_shared_relationships_transaction>("transaction", Transaction);
        }
    }
}
#pragma warning restore CS0618
