// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Persona.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ReportTemplatePhoneNumberType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "report-template/phone-number")]
        #pragma warning disable CS1591
        ReportTemplatePhoneNumber,
        #pragma warning restore CS1591
    }
}
