// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Persona.OpenApiClient.Models
{
    /// <summary>The type of history entry</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ReportHistoryDismiss_type
    {
        [EnumMember(Value = "dismiss")]
        #pragma warning disable CS1591
        Dismiss,
        #pragma warning restore CS1591
    }
}
