// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Persona.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ReportPhoneRiskAttributes : global::Soenneker.Persona.OpenApiClient.Models.ReportSharedAttributes, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The phoneCarrier property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PhoneCarrier { get; set; }
#nullable restore
#else
        public string PhoneCarrier { get; set; }
#endif
        /// <summary>The input phone number of the search</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PhoneNumber { get; set; }
#nullable restore
#else
        public string PhoneNumber { get; set; }
#endif
        /// <summary>Assessment of the phone number&apos;s risk (low - high)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PhoneRiskLevel { get; set; }
#nullable restore
#else
        public string PhoneRiskLevel { get; set; }
#endif
        /// <summary>Possible values:- block- allow- flagDo not assume this is a static enumeration; Persona may add newvalues in the future without a versioned update.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PhoneRiskRecommendation { get; set; }
#nullable restore
#else
        public string PhoneRiskRecommendation { get; set; }
#endif
        /// <summary>Risk score out of 1000</summary>
        public int? PhoneRiskScore { get; set; }
        /// <summary>The risk of a fraudulent SIM swapPossible values:- very-low- low- medium- high- N/ADo not assume this is a static enumeration; Persona may add newvalues in the future without a versioned update.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PhoneRiskSimSwap { get; set; }
#nullable restore
#else
        public string PhoneRiskSimSwap { get; set; }
#endif
        /// <summary>Possible values:- FIXED_LINE- MOBILE- PREPAID- TOLL_FREE- VOIP- PAGER- PAYPHONE- INVALID- RESTRICTED_PREMIUM- PERSONAL- VOICEMAIL- OTHERDo not assume this is a static enumeration; Persona may add newvalues in the future without a versioned update.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PhoneType { get; set; }
#nullable restore
#else
        public string PhoneType { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Persona.OpenApiClient.Models.ReportPhoneRiskAttributes"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::Soenneker.Persona.OpenApiClient.Models.ReportPhoneRiskAttributes CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Persona.OpenApiClient.Models.ReportPhoneRiskAttributes();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "phone-carrier", n => { PhoneCarrier = n.GetStringValue(); } },
                { "phone-number", n => { PhoneNumber = n.GetStringValue(); } },
                { "phone-risk-level", n => { PhoneRiskLevel = n.GetStringValue(); } },
                { "phone-risk-recommendation", n => { PhoneRiskRecommendation = n.GetStringValue(); } },
                { "phone-risk-score", n => { PhoneRiskScore = n.GetIntValue(); } },
                { "phone-risk-sim-swap", n => { PhoneRiskSimSwap = n.GetStringValue(); } },
                { "phone-type", n => { PhoneType = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteStringValue("phone-carrier", PhoneCarrier);
            writer.WriteStringValue("phone-number", PhoneNumber);
            writer.WriteStringValue("phone-risk-level", PhoneRiskLevel);
            writer.WriteStringValue("phone-risk-recommendation", PhoneRiskRecommendation);
            writer.WriteIntValue("phone-risk-score", PhoneRiskScore);
            writer.WriteStringValue("phone-risk-sim-swap", PhoneRiskSimSwap);
            writer.WriteStringValue("phone-type", PhoneType);
        }
    }
}
#pragma warning restore CS0618
