// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Persona.OpenApiClient.Models
{
    /// <summary>
    /// Requires `phone-number`, or `email-address`, or all of `name-first`, `name-last`, `address-city`, and `address-subdivision`.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ReportProfileNonAuthoritativeRequestAttributes_query : IParsable
    {
        /// <summary>City</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AddressCity { get; set; }
#nullable restore
#else
        public string AddressCity { get; set; }
#endif
        /// <summary>Subnational division (such as a state or province) of the country of residence.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AddressSubdivision { get; set; }
#nullable restore
#else
        public string AddressSubdivision { get; set; }
#endif
        /// <summary>Email address of the individual to search.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EmailAddress { get; set; }
#nullable restore
#else
        public string EmailAddress { get; set; }
#endif
        /// <summary>The first name of the individual to search.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NameFirst { get; set; }
#nullable restore
#else
        public string NameFirst { get; set; }
#endif
        /// <summary>The last name of the individual to search.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NameLast { get; set; }
#nullable restore
#else
        public string NameLast { get; set; }
#endif
        /// <summary>Phone number of the individual to search.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PhoneNumber { get; set; }
#nullable restore
#else
        public string PhoneNumber { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Persona.OpenApiClient.Models.ReportProfileNonAuthoritativeRequestAttributes_query"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Persona.OpenApiClient.Models.ReportProfileNonAuthoritativeRequestAttributes_query CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Persona.OpenApiClient.Models.ReportProfileNonAuthoritativeRequestAttributes_query();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "address-city", n => { AddressCity = n.GetStringValue(); } },
                { "address-subdivision", n => { AddressSubdivision = n.GetStringValue(); } },
                { "email-address", n => { EmailAddress = n.GetStringValue(); } },
                { "name-first", n => { NameFirst = n.GetStringValue(); } },
                { "name-last", n => { NameLast = n.GetStringValue(); } },
                { "phone-number", n => { PhoneNumber = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("address-city", AddressCity);
            writer.WriteStringValue("address-subdivision", AddressSubdivision);
            writer.WriteStringValue("email-address", EmailAddress);
            writer.WriteStringValue("name-first", NameFirst);
            writer.WriteStringValue("name-last", NameLast);
            writer.WriteStringValue("phone-number", PhoneNumber);
        }
    }
}
#pragma warning restore CS0618
