// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Persona.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Report_politically_exposed_person_request_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "report/politically-exposed-person")]
        #pragma warning disable CS1591
        ReportPoliticallyExposedPerson,
        #pragma warning restore CS1591
    }
}
