// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Persona.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ReportTemplateBusinessLookup_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "report-template/business-lookup")]
        #pragma warning disable CS1591
        ReportTemplateBusinessLookup,
        #pragma warning restore CS1591
    }
}
