// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Persona.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Report_address_lookup_attributes : global::Soenneker.Persona.OpenApiClient.Models.Report_shared_attributes, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>City</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AddressCity { get; set; }
#nullable restore
#else
        public string AddressCity { get; set; }
#endif
        /// <summary>The name of an individual at this location.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Addressee { get; set; }
#nullable restore
#else
        public string Addressee { get; set; }
#endif
        /// <summary>ZIP or postal code.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AddressPostalCode { get; set; }
#nullable restore
#else
        public string AddressPostalCode { get; set; }
#endif
        /// <summary>Address line 1 (e.g., street, PO Box, or company name).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AddressStreet1 { get; set; }
#nullable restore
#else
        public string AddressStreet1 { get; set; }
#endif
        /// <summary>Address line 2 (e.g., apartment, suite, unit, or building).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AddressStreet2 { get; set; }
#nullable restore
#else
        public string AddressStreet2 { get; set; }
#endif
        /// <summary>Subnational division of a country, such as a state or province.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AddressSubdivision { get; set; }
#nullable restore
#else
        public string AddressSubdivision { get; set; }
#endif
        /// <summary>The analysisActive property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AnalysisActive { get; set; }
#nullable restore
#else
        public string AnalysisActive { get; set; }
#endif
        /// <summary>The analysisDpvCmra property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AnalysisDpvCmra { get; set; }
#nullable restore
#else
        public string AnalysisDpvCmra { get; set; }
#endif
        /// <summary>The analysisDpvFootnotes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? AnalysisDpvFootnotes { get; set; }
#nullable restore
#else
        public List<string> AnalysisDpvFootnotes { get; set; }
#endif
        /// <summary>The analysisDpvFootnotesDecoded property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? AnalysisDpvFootnotesDecoded { get; set; }
#nullable restore
#else
        public List<string> AnalysisDpvFootnotesDecoded { get; set; }
#endif
        /// <summary>The analysisDpvMatchCode property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AnalysisDpvMatchCode { get; set; }
#nullable restore
#else
        public string AnalysisDpvMatchCode { get; set; }
#endif
        /// <summary>The analysisDpvMatchCodeDecoded property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AnalysisDpvMatchCodeDecoded { get; set; }
#nullable restore
#else
        public string AnalysisDpvMatchCodeDecoded { get; set; }
#endif
        /// <summary>The analysisDpvVacant property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AnalysisDpvVacant { get; set; }
#nullable restore
#else
        public string AnalysisDpvVacant { get; set; }
#endif
        /// <summary>The analysisFootnotes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? AnalysisFootnotes { get; set; }
#nullable restore
#else
        public List<string> AnalysisFootnotes { get; set; }
#endif
        /// <summary>The analysisFootnotesDecoded property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? AnalysisFootnotesDecoded { get; set; }
#nullable restore
#else
        public List<string> AnalysisFootnotesDecoded { get; set; }
#endif
        /// <summary>The analysisLacsLinkCode property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AnalysisLacsLinkCode { get; set; }
#nullable restore
#else
        public string AnalysisLacsLinkCode { get; set; }
#endif
        /// <summary>The analysisLacsLinkCodeDecoded property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AnalysisLacsLinkCodeDecoded { get; set; }
#nullable restore
#else
        public string AnalysisLacsLinkCodeDecoded { get; set; }
#endif
        /// <summary>The analysisLacsLinkIndicator property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AnalysisLacsLinkIndicator { get; set; }
#nullable restore
#else
        public string AnalysisLacsLinkIndicator { get; set; }
#endif
        /// <summary>The analysisLacsLinkIndicatorDecoded property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AnalysisLacsLinkIndicatorDecoded { get; set; }
#nullable restore
#else
        public string AnalysisLacsLinkIndicatorDecoded { get; set; }
#endif
        /// <summary>The analysisSuiteLinkMatch property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AnalysisSuiteLinkMatch { get; set; }
#nullable restore
#else
        public string AnalysisSuiteLinkMatch { get; set; }
#endif
        /// <summary>The errorMessage property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ErrorMessage { get; set; }
#nullable restore
#else
        public string ErrorMessage { get; set; }
#endif
        /// <summary>The metadataBuildingDefaultIndicator property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MetadataBuildingDefaultIndicator { get; set; }
#nullable restore
#else
        public string MetadataBuildingDefaultIndicator { get; set; }
#endif
        /// <summary>The metadataCarrierRoute property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MetadataCarrierRoute { get; set; }
#nullable restore
#else
        public string MetadataCarrierRoute { get; set; }
#endif
        /// <summary>The metadataCarrierRouteType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MetadataCarrierRouteType { get; set; }
#nullable restore
#else
        public string MetadataCarrierRouteType { get; set; }
#endif
        /// <summary>The metadataCongressionalDistrict property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MetadataCongressionalDistrict { get; set; }
#nullable restore
#else
        public string MetadataCongressionalDistrict { get; set; }
#endif
        /// <summary>The metadataCountyFips property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MetadataCountyFips { get; set; }
#nullable restore
#else
        public string MetadataCountyFips { get; set; }
#endif
        /// <summary>The metadataCountyName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MetadataCountyName { get; set; }
#nullable restore
#else
        public string MetadataCountyName { get; set; }
#endif
        /// <summary>The metadataEwsMatch property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MetadataEwsMatch { get; set; }
#nullable restore
#else
        public string MetadataEwsMatch { get; set; }
#endif
        /// <summary>The metadataLatitude property</summary>
        public double? MetadataLatitude { get; set; }
        /// <summary>The metadataLongitude property</summary>
        public double? MetadataLongitude { get; set; }
        /// <summary>The metadataObeysDaylightSavings property</summary>
        public bool? MetadataObeysDaylightSavings { get; set; }
        /// <summary>The metadataPrecision property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MetadataPrecision { get; set; }
#nullable restore
#else
        public string MetadataPrecision { get; set; }
#endif
        /// <summary>The metadataRecordType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MetadataRecordType { get; set; }
#nullable restore
#else
        public string MetadataRecordType { get; set; }
#endif
        /// <summary>The metadataResidentialDeliveryIndicator property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MetadataResidentialDeliveryIndicator { get; set; }
#nullable restore
#else
        public string MetadataResidentialDeliveryIndicator { get; set; }
#endif
        /// <summary>The metadataTimeZone property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MetadataTimeZone { get; set; }
#nullable restore
#else
        public string MetadataTimeZone { get; set; }
#endif
        /// <summary>The metadataUtcOffset property</summary>
        public int? MetadataUtcOffset { get; set; }
        /// <summary>The metadataZipType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MetadataZipType { get; set; }
#nullable restore
#else
        public string MetadataZipType { get; set; }
#endif
        /// <summary>The resolvedAddressCity property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ResolvedAddressCity { get; set; }
#nullable restore
#else
        public string ResolvedAddressCity { get; set; }
#endif
        /// <summary>The resolvedAddressee property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ResolvedAddressee { get; set; }
#nullable restore
#else
        public string ResolvedAddressee { get; set; }
#endif
        /// <summary>The resolvedAddressPostalCode property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ResolvedAddressPostalCode { get; set; }
#nullable restore
#else
        public string ResolvedAddressPostalCode { get; set; }
#endif
        /// <summary>The resolvedAddressStreet1 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ResolvedAddressStreet1 { get; set; }
#nullable restore
#else
        public string ResolvedAddressStreet1 { get; set; }
#endif
        /// <summary>The resolvedAddressStreet2 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ResolvedAddressStreet2 { get; set; }
#nullable restore
#else
        public string ResolvedAddressStreet2 { get; set; }
#endif
        /// <summary>The resolvedAddressSubdivision property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ResolvedAddressSubdivision { get; set; }
#nullable restore
#else
        public string ResolvedAddressSubdivision { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Persona.OpenApiClient.Models.Report_address_lookup_attributes"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::Soenneker.Persona.OpenApiClient.Models.Report_address_lookup_attributes CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Persona.OpenApiClient.Models.Report_address_lookup_attributes();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "address-city", n => { AddressCity = n.GetStringValue(); } },
                { "address-postal-code", n => { AddressPostalCode = n.GetStringValue(); } },
                { "address-street-1", n => { AddressStreet1 = n.GetStringValue(); } },
                { "address-street-2", n => { AddressStreet2 = n.GetStringValue(); } },
                { "address-subdivision", n => { AddressSubdivision = n.GetStringValue(); } },
                { "addressee", n => { Addressee = n.GetStringValue(); } },
                { "analysis-active", n => { AnalysisActive = n.GetStringValue(); } },
                { "analysis-dpv-cmra", n => { AnalysisDpvCmra = n.GetStringValue(); } },
                { "analysis-dpv-footnotes", n => { AnalysisDpvFootnotes = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "analysis-dpv-footnotes-decoded", n => { AnalysisDpvFootnotesDecoded = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "analysis-dpv-match-code", n => { AnalysisDpvMatchCode = n.GetStringValue(); } },
                { "analysis-dpv-match-code-decoded", n => { AnalysisDpvMatchCodeDecoded = n.GetStringValue(); } },
                { "analysis-dpv-vacant", n => { AnalysisDpvVacant = n.GetStringValue(); } },
                { "analysis-footnotes", n => { AnalysisFootnotes = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "analysis-footnotes-decoded", n => { AnalysisFootnotesDecoded = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "analysis-lacs-link-code", n => { AnalysisLacsLinkCode = n.GetStringValue(); } },
                { "analysis-lacs-link-code-decoded", n => { AnalysisLacsLinkCodeDecoded = n.GetStringValue(); } },
                { "analysis-lacs-link-indicator", n => { AnalysisLacsLinkIndicator = n.GetStringValue(); } },
                { "analysis-lacs-link-indicator-decoded", n => { AnalysisLacsLinkIndicatorDecoded = n.GetStringValue(); } },
                { "analysis-suite-link-match", n => { AnalysisSuiteLinkMatch = n.GetStringValue(); } },
                { "error-message", n => { ErrorMessage = n.GetStringValue(); } },
                { "metadata-building-default-indicator", n => { MetadataBuildingDefaultIndicator = n.GetStringValue(); } },
                { "metadata-carrier-route", n => { MetadataCarrierRoute = n.GetStringValue(); } },
                { "metadata-carrier-route-type", n => { MetadataCarrierRouteType = n.GetStringValue(); } },
                { "metadata-congressional-district", n => { MetadataCongressionalDistrict = n.GetStringValue(); } },
                { "metadata-county-fips", n => { MetadataCountyFips = n.GetStringValue(); } },
                { "metadata-county-name", n => { MetadataCountyName = n.GetStringValue(); } },
                { "metadata-ews-match", n => { MetadataEwsMatch = n.GetStringValue(); } },
                { "metadata-latitude", n => { MetadataLatitude = n.GetDoubleValue(); } },
                { "metadata-longitude", n => { MetadataLongitude = n.GetDoubleValue(); } },
                { "metadata-obeys-daylight-savings", n => { MetadataObeysDaylightSavings = n.GetBoolValue(); } },
                { "metadata-precision", n => { MetadataPrecision = n.GetStringValue(); } },
                { "metadata-record-type", n => { MetadataRecordType = n.GetStringValue(); } },
                { "metadata-residential-delivery-indicator", n => { MetadataResidentialDeliveryIndicator = n.GetStringValue(); } },
                { "metadata-time-zone", n => { MetadataTimeZone = n.GetStringValue(); } },
                { "metadata-utc-offset", n => { MetadataUtcOffset = n.GetIntValue(); } },
                { "metadata-zip-type", n => { MetadataZipType = n.GetStringValue(); } },
                { "resolved-address-city", n => { ResolvedAddressCity = n.GetStringValue(); } },
                { "resolved-address-postal-code", n => { ResolvedAddressPostalCode = n.GetStringValue(); } },
                { "resolved-address-street-1", n => { ResolvedAddressStreet1 = n.GetStringValue(); } },
                { "resolved-address-street-2", n => { ResolvedAddressStreet2 = n.GetStringValue(); } },
                { "resolved-address-subdivision", n => { ResolvedAddressSubdivision = n.GetStringValue(); } },
                { "resolved-addressee", n => { ResolvedAddressee = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteStringValue("address-city", AddressCity);
            writer.WriteStringValue("addressee", Addressee);
            writer.WriteStringValue("address-postal-code", AddressPostalCode);
            writer.WriteStringValue("address-street-1", AddressStreet1);
            writer.WriteStringValue("address-street-2", AddressStreet2);
            writer.WriteStringValue("address-subdivision", AddressSubdivision);
            writer.WriteStringValue("analysis-active", AnalysisActive);
            writer.WriteStringValue("analysis-dpv-cmra", AnalysisDpvCmra);
            writer.WriteCollectionOfPrimitiveValues<string>("analysis-dpv-footnotes", AnalysisDpvFootnotes);
            writer.WriteCollectionOfPrimitiveValues<string>("analysis-dpv-footnotes-decoded", AnalysisDpvFootnotesDecoded);
            writer.WriteStringValue("analysis-dpv-match-code", AnalysisDpvMatchCode);
            writer.WriteStringValue("analysis-dpv-match-code-decoded", AnalysisDpvMatchCodeDecoded);
            writer.WriteStringValue("analysis-dpv-vacant", AnalysisDpvVacant);
            writer.WriteCollectionOfPrimitiveValues<string>("analysis-footnotes", AnalysisFootnotes);
            writer.WriteCollectionOfPrimitiveValues<string>("analysis-footnotes-decoded", AnalysisFootnotesDecoded);
            writer.WriteStringValue("analysis-lacs-link-code", AnalysisLacsLinkCode);
            writer.WriteStringValue("analysis-lacs-link-code-decoded", AnalysisLacsLinkCodeDecoded);
            writer.WriteStringValue("analysis-lacs-link-indicator", AnalysisLacsLinkIndicator);
            writer.WriteStringValue("analysis-lacs-link-indicator-decoded", AnalysisLacsLinkIndicatorDecoded);
            writer.WriteStringValue("analysis-suite-link-match", AnalysisSuiteLinkMatch);
            writer.WriteStringValue("error-message", ErrorMessage);
            writer.WriteStringValue("metadata-building-default-indicator", MetadataBuildingDefaultIndicator);
            writer.WriteStringValue("metadata-carrier-route", MetadataCarrierRoute);
            writer.WriteStringValue("metadata-carrier-route-type", MetadataCarrierRouteType);
            writer.WriteStringValue("metadata-congressional-district", MetadataCongressionalDistrict);
            writer.WriteStringValue("metadata-county-fips", MetadataCountyFips);
            writer.WriteStringValue("metadata-county-name", MetadataCountyName);
            writer.WriteStringValue("metadata-ews-match", MetadataEwsMatch);
            writer.WriteDoubleValue("metadata-latitude", MetadataLatitude);
            writer.WriteDoubleValue("metadata-longitude", MetadataLongitude);
            writer.WriteBoolValue("metadata-obeys-daylight-savings", MetadataObeysDaylightSavings);
            writer.WriteStringValue("metadata-precision", MetadataPrecision);
            writer.WriteStringValue("metadata-record-type", MetadataRecordType);
            writer.WriteStringValue("metadata-residential-delivery-indicator", MetadataResidentialDeliveryIndicator);
            writer.WriteStringValue("metadata-time-zone", MetadataTimeZone);
            writer.WriteIntValue("metadata-utc-offset", MetadataUtcOffset);
            writer.WriteStringValue("metadata-zip-type", MetadataZipType);
            writer.WriteStringValue("resolved-address-city", ResolvedAddressCity);
            writer.WriteStringValue("resolved-addressee", ResolvedAddressee);
            writer.WriteStringValue("resolved-address-postal-code", ResolvedAddressPostalCode);
            writer.WriteStringValue("resolved-address-street-1", ResolvedAddressStreet1);
            writer.WriteStringValue("resolved-address-street-2", ResolvedAddressStreet2);
            writer.WriteStringValue("resolved-address-subdivision", ResolvedAddressSubdivision);
        }
    }
}
#pragma warning restore CS0618
