// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Persona.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Report_template_adverse_media_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "report-template/adverse-media")]
        #pragma warning disable CS1591
        ReportTemplateAdverseMedia,
        #pragma warning restore CS1591
    }
}
