// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Persona.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class TransactionRelationships : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Objects involved in this Transaction&apos;s related Workflow runs. Will include a maximum of 100 related objects.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Persona.OpenApiClient.Models.TransactionRelationshipsRelatedObjects? RelatedObjects { get; set; }
#nullable restore
#else
        public global::Soenneker.Persona.OpenApiClient.Models.TransactionRelationshipsRelatedObjects RelatedObjects { get; set; }
#endif
        /// <summary>The entity that reviewed the transaction</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Persona.OpenApiClient.Models.TransactionRelationshipsReviewer? Reviewer { get; set; }
#nullable restore
#else
        public global::Soenneker.Persona.OpenApiClient.Models.TransactionRelationshipsReviewer Reviewer { get; set; }
#endif
        /// <summary>The transactionLabel property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Persona.OpenApiClient.Models.TransactionRelationshipsTransactionLabel? TransactionLabel { get; set; }
#nullable restore
#else
        public global::Soenneker.Persona.OpenApiClient.Models.TransactionRelationshipsTransactionLabel TransactionLabel { get; set; }
#endif
        /// <summary>The transactionType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Persona.OpenApiClient.Models.TransactionRelationshipsTransactionType? TransactionType { get; set; }
#nullable restore
#else
        public global::Soenneker.Persona.OpenApiClient.Models.TransactionRelationshipsTransactionType TransactionType { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Persona.OpenApiClient.Models.TransactionRelationships"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Persona.OpenApiClient.Models.TransactionRelationships CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Persona.OpenApiClient.Models.TransactionRelationships();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "related-objects", n => { RelatedObjects = n.GetObjectValue<global::Soenneker.Persona.OpenApiClient.Models.TransactionRelationshipsRelatedObjects>(global::Soenneker.Persona.OpenApiClient.Models.TransactionRelationshipsRelatedObjects.CreateFromDiscriminatorValue); } },
                { "reviewer", n => { Reviewer = n.GetObjectValue<global::Soenneker.Persona.OpenApiClient.Models.TransactionRelationshipsReviewer>(global::Soenneker.Persona.OpenApiClient.Models.TransactionRelationshipsReviewer.CreateFromDiscriminatorValue); } },
                { "transaction-label", n => { TransactionLabel = n.GetObjectValue<global::Soenneker.Persona.OpenApiClient.Models.TransactionRelationshipsTransactionLabel>(global::Soenneker.Persona.OpenApiClient.Models.TransactionRelationshipsTransactionLabel.CreateFromDiscriminatorValue); } },
                { "transaction-type", n => { TransactionType = n.GetObjectValue<global::Soenneker.Persona.OpenApiClient.Models.TransactionRelationshipsTransactionType>(global::Soenneker.Persona.OpenApiClient.Models.TransactionRelationshipsTransactionType.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Persona.OpenApiClient.Models.TransactionRelationshipsRelatedObjects>("related-objects", RelatedObjects);
            writer.WriteObjectValue<global::Soenneker.Persona.OpenApiClient.Models.TransactionRelationshipsReviewer>("reviewer", Reviewer);
            writer.WriteObjectValue<global::Soenneker.Persona.OpenApiClient.Models.TransactionRelationshipsTransactionLabel>("transaction-label", TransactionLabel);
            writer.WriteObjectValue<global::Soenneker.Persona.OpenApiClient.Models.TransactionRelationshipsTransactionType>("transaction-type", TransactionType);
        }
    }
}
#pragma warning restore CS0618
