// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Persona.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum VerificationUpdatedTagsName
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "verification.updated-tags")]
        #pragma warning disable CS1591
        VerificationUpdatedTags,
        #pragma warning restore CS1591
    }
}
