// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Persona.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum VerificationPersonaFffInquiry_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "verification/persona-fff-inquiry")]
        #pragma warning disable CS1591
        VerificationPersonaFffInquiry,
        #pragma warning restore CS1591
    }
}
