// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Persona.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum VerificationDigitalIdConnectId_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "verification/digital-id-connect-id")]
        #pragma warning disable CS1591
        VerificationDigitalIdConnectId,
        #pragma warning restore CS1591
    }
}
