// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Persona.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Verification_database_tin_attributes : global::Soenneker.Persona.OpenApiClient.Models.Verification_shared_attributes, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The nameBusiness property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NameBusiness { get; set; }
#nullable restore
#else
        public string NameBusiness { get; set; }
#endif
        /// <summary>The nameFirst property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NameFirst { get; set; }
#nullable restore
#else
        public string NameFirst { get; set; }
#endif
        /// <summary>The nameLast property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NameLast { get; set; }
#nullable restore
#else
        public string NameLast { get; set; }
#endif
        /// <summary>The tin property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Tin { get; set; }
#nullable restore
#else
        public string Tin { get; set; }
#endif
        /// <summary>The tinType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TinType { get; set; }
#nullable restore
#else
        public string TinType { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Persona.OpenApiClient.Models.Verification_database_tin_attributes"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::Soenneker.Persona.OpenApiClient.Models.Verification_database_tin_attributes CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Persona.OpenApiClient.Models.Verification_database_tin_attributes();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "name-business", n => { NameBusiness = n.GetStringValue(); } },
                { "name-first", n => { NameFirst = n.GetStringValue(); } },
                { "name-last", n => { NameLast = n.GetStringValue(); } },
                { "tin", n => { Tin = n.GetStringValue(); } },
                { "tin-type", n => { TinType = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteStringValue("name-business", NameBusiness);
            writer.WriteStringValue("name-first", NameFirst);
            writer.WriteStringValue("name-last", NameLast);
            writer.WriteStringValue("tin", Tin);
            writer.WriteStringValue("tin-type", TinType);
        }
    }
}
#pragma warning restore CS0618
