// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Persona.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum VerificationSubmittedName
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "verification.submitted")]
        #pragma warning disable CS1591
        VerificationSubmitted,
        #pragma warning restore CS1591
    }
}
