// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Persona.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class WebhookReportScreeningReadyRequestDataAttributes : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Unused for this event; always an empty object.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Persona.OpenApiClient.Models.WebhookReportScreeningReadyRequestDataAttributesContext? Context { get; set; }
#nullable restore
#else
        public global::Soenneker.Persona.OpenApiClient.Models.WebhookReportScreeningReadyRequestDataAttributesContext Context { get; set; }
#endif
        /// <summary>Datetime when the event was created.</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The name property</summary>
        public global::Soenneker.Persona.OpenApiClient.Models.ReportScreeningReadyName? Name { get; set; }
        /// <summary>The payload property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Persona.OpenApiClient.Models.WebhookReportScreeningReadyRequestDataAttributesPayload? Payload { get; set; }
#nullable restore
#else
        public global::Soenneker.Persona.OpenApiClient.Models.WebhookReportScreeningReadyRequestDataAttributesPayload Payload { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Persona.OpenApiClient.Models.WebhookReportScreeningReadyRequestDataAttributes"/> and sets the default values.
        /// </summary>
        public WebhookReportScreeningReadyRequestDataAttributes()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Persona.OpenApiClient.Models.WebhookReportScreeningReadyRequestDataAttributes"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Persona.OpenApiClient.Models.WebhookReportScreeningReadyRequestDataAttributes CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Persona.OpenApiClient.Models.WebhookReportScreeningReadyRequestDataAttributes();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "context", n => { Context = n.GetObjectValue<global::Soenneker.Persona.OpenApiClient.Models.WebhookReportScreeningReadyRequestDataAttributesContext>(global::Soenneker.Persona.OpenApiClient.Models.WebhookReportScreeningReadyRequestDataAttributesContext.CreateFromDiscriminatorValue); } },
                { "created-at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "name", n => { Name = n.GetEnumValue<global::Soenneker.Persona.OpenApiClient.Models.ReportScreeningReadyName>(); } },
                { "payload", n => { Payload = n.GetObjectValue<global::Soenneker.Persona.OpenApiClient.Models.WebhookReportScreeningReadyRequestDataAttributesPayload>(global::Soenneker.Persona.OpenApiClient.Models.WebhookReportScreeningReadyRequestDataAttributesPayload.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Persona.OpenApiClient.Models.WebhookReportScreeningReadyRequestDataAttributesContext>("context", Context);
            writer.WriteDateTimeOffsetValue("created-at", CreatedAt);
            writer.WriteEnumValue<global::Soenneker.Persona.OpenApiClient.Models.ReportScreeningReadyName>("name", Name);
            writer.WriteObjectValue<global::Soenneker.Persona.OpenApiClient.Models.WebhookReportScreeningReadyRequestDataAttributesPayload>("payload", Payload);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
