// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Persona.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Webhook_request_attributes_enabledEvents
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "*")]
        #pragma warning disable CS1591
        Asterisk,
        #pragma warning restore CS1591
        [EnumMember(Value = "account.created")]
        #pragma warning disable CS1591
        AccountCreated,
        #pragma warning restore CS1591
        [EnumMember(Value = "account.redacted")]
        #pragma warning disable CS1591
        AccountRedacted,
        #pragma warning restore CS1591
        [EnumMember(Value = "account.archived")]
        #pragma warning disable CS1591
        AccountArchived,
        #pragma warning restore CS1591
        [EnumMember(Value = "account.restored")]
        #pragma warning disable CS1591
        AccountRestored,
        #pragma warning restore CS1591
        [EnumMember(Value = "account.consolidated")]
        #pragma warning disable CS1591
        AccountConsolidated,
        #pragma warning restore CS1591
        [EnumMember(Value = "account.tag-added")]
        #pragma warning disable CS1591
        AccountTagAdded,
        #pragma warning restore CS1591
        [EnumMember(Value = "account.tag-removed")]
        #pragma warning disable CS1591
        AccountTagRemoved,
        #pragma warning restore CS1591
        [EnumMember(Value = "case.created")]
        #pragma warning disable CS1591
        CaseCreated,
        #pragma warning restore CS1591
        [EnumMember(Value = "case.assigned")]
        #pragma warning disable CS1591
        CaseAssigned,
        #pragma warning restore CS1591
        [EnumMember(Value = "case.resolved")]
        #pragma warning disable CS1591
        CaseResolved,
        #pragma warning restore CS1591
        [EnumMember(Value = "case.reopened")]
        #pragma warning disable CS1591
        CaseReopened,
        #pragma warning restore CS1591
        [EnumMember(Value = "case.updated")]
        #pragma warning disable CS1591
        CaseUpdated,
        #pragma warning restore CS1591
        [EnumMember(Value = "document.created")]
        #pragma warning disable CS1591
        DocumentCreated,
        #pragma warning restore CS1591
        [EnumMember(Value = "document.submitted")]
        #pragma warning disable CS1591
        DocumentSubmitted,
        #pragma warning restore CS1591
        [EnumMember(Value = "document.processed")]
        #pragma warning disable CS1591
        DocumentProcessed,
        #pragma warning restore CS1591
        [EnumMember(Value = "document.errored")]
        #pragma warning disable CS1591
        DocumentErrored,
        #pragma warning restore CS1591
        [EnumMember(Value = "importer-pipeline-run.started")]
        #pragma warning disable CS1591
        ImporterPipelineRunStarted,
        #pragma warning restore CS1591
        [EnumMember(Value = "importer-pipeline-run.completed")]
        #pragma warning disable CS1591
        ImporterPipelineRunCompleted,
        #pragma warning restore CS1591
        [EnumMember(Value = "importer-pipeline-run.errored")]
        #pragma warning disable CS1591
        ImporterPipelineRunErrored,
        #pragma warning restore CS1591
        [EnumMember(Value = "importer-pipeline-run.canceled")]
        #pragma warning disable CS1591
        ImporterPipelineRunCanceled,
        #pragma warning restore CS1591
        [EnumMember(Value = "importer-pipeline-run.paused")]
        #pragma warning disable CS1591
        ImporterPipelineRunPaused,
        #pragma warning restore CS1591
        [EnumMember(Value = "importer-pipeline-run.resumed")]
        #pragma warning disable CS1591
        ImporterPipelineRunResumed,
        #pragma warning restore CS1591
        [EnumMember(Value = "inquiry.created")]
        #pragma warning disable CS1591
        InquiryCreated,
        #pragma warning restore CS1591
        [EnumMember(Value = "inquiry.expired")]
        #pragma warning disable CS1591
        InquiryExpired,
        #pragma warning restore CS1591
        [EnumMember(Value = "inquiry.completed")]
        #pragma warning disable CS1591
        InquiryCompleted,
        #pragma warning restore CS1591
        [EnumMember(Value = "inquiry.failed")]
        #pragma warning disable CS1591
        InquiryFailed,
        #pragma warning restore CS1591
        [EnumMember(Value = "inquiry.marked-for-review")]
        #pragma warning disable CS1591
        InquiryMarkedForReview,
        #pragma warning restore CS1591
        [EnumMember(Value = "inquiry.approved")]
        #pragma warning disable CS1591
        InquiryApproved,
        #pragma warning restore CS1591
        [EnumMember(Value = "inquiry.declined")]
        #pragma warning disable CS1591
        InquiryDeclined,
        #pragma warning restore CS1591
        [EnumMember(Value = "inquiry.transitioned")]
        #pragma warning disable CS1591
        InquiryTransitioned,
        #pragma warning restore CS1591
        [EnumMember(Value = "inquiry-session.started")]
        #pragma warning disable CS1591
        InquirySessionStarted,
        #pragma warning restore CS1591
        [EnumMember(Value = "inquiry-session.expired")]
        #pragma warning disable CS1591
        InquirySessionExpired,
        #pragma warning restore CS1591
        [EnumMember(Value = "inquiry-session.canceled")]
        #pragma warning disable CS1591
        InquirySessionCanceled,
        #pragma warning restore CS1591
        [EnumMember(Value = "report/address-lookup.ready")]
        #pragma warning disable CS1591
        ReportAddressLookupReady,
        #pragma warning restore CS1591
        [EnumMember(Value = "report/address-lookup.errored")]
        #pragma warning disable CS1591
        ReportAddressLookupErrored,
        #pragma warning restore CS1591
        [EnumMember(Value = "report/adverse-media.matched")]
        #pragma warning disable CS1591
        ReportAdverseMediaMatched,
        #pragma warning restore CS1591
        [EnumMember(Value = "report/adverse-media.ready")]
        #pragma warning disable CS1591
        ReportAdverseMediaReady,
        #pragma warning restore CS1591
        [EnumMember(Value = "report/adverse-media.errored")]
        #pragma warning disable CS1591
        ReportAdverseMediaErrored,
        #pragma warning restore CS1591
        [EnumMember(Value = "report/business-adverse-media.matched")]
        #pragma warning disable CS1591
        ReportBusinessAdverseMediaMatched,
        #pragma warning restore CS1591
        [EnumMember(Value = "report/business-adverse-media.ready")]
        #pragma warning disable CS1591
        ReportBusinessAdverseMediaReady,
        #pragma warning restore CS1591
        [EnumMember(Value = "report/business-adverse-media.errored")]
        #pragma warning disable CS1591
        ReportBusinessAdverseMediaErrored,
        #pragma warning restore CS1591
        [EnumMember(Value = "report/business-watchlist.ready")]
        #pragma warning disable CS1591
        ReportBusinessWatchlistReady,
        #pragma warning restore CS1591
        [EnumMember(Value = "report/business-watchlist.matched")]
        #pragma warning disable CS1591
        ReportBusinessWatchlistMatched,
        #pragma warning restore CS1591
        [EnumMember(Value = "report/business-watchlist.errored")]
        #pragma warning disable CS1591
        ReportBusinessWatchlistErrored,
        #pragma warning restore CS1591
        [EnumMember(Value = "report/email-address.ready")]
        #pragma warning disable CS1591
        ReportEmailAddressReady,
        #pragma warning restore CS1591
        [EnumMember(Value = "report/email-address.errored")]
        #pragma warning disable CS1591
        ReportEmailAddressErrored,
        #pragma warning restore CS1591
        [EnumMember(Value = "report/phone-number.ready")]
        #pragma warning disable CS1591
        ReportPhoneNumberReady,
        #pragma warning restore CS1591
        [EnumMember(Value = "report/phone-number.errored")]
        #pragma warning disable CS1591
        ReportPhoneNumberErrored,
        #pragma warning restore CS1591
        [EnumMember(Value = "report/profile.ready")]
        #pragma warning disable CS1591
        ReportProfileReady,
        #pragma warning restore CS1591
        [EnumMember(Value = "report/profile.errored")]
        #pragma warning disable CS1591
        ReportProfileErrored,
        #pragma warning restore CS1591
        [EnumMember(Value = "report/politically-exposed-person.matched")]
        #pragma warning disable CS1591
        ReportPoliticallyExposedPersonMatched,
        #pragma warning restore CS1591
        [EnumMember(Value = "report/politically-exposed-person.ready")]
        #pragma warning disable CS1591
        ReportPoliticallyExposedPersonReady,
        #pragma warning restore CS1591
        [EnumMember(Value = "report/politically-exposed-person.errored")]
        #pragma warning disable CS1591
        ReportPoliticallyExposedPersonErrored,
        #pragma warning restore CS1591
        [EnumMember(Value = "report/watchlist.matched")]
        #pragma warning disable CS1591
        ReportWatchlistMatched,
        #pragma warning restore CS1591
        [EnumMember(Value = "report/watchlist.ready")]
        #pragma warning disable CS1591
        ReportWatchlistReady,
        #pragma warning restore CS1591
        [EnumMember(Value = "report/watchlist.errored")]
        #pragma warning disable CS1591
        ReportWatchlistErrored,
        #pragma warning restore CS1591
        [EnumMember(Value = "selfie.created")]
        #pragma warning disable CS1591
        SelfieCreated,
        #pragma warning restore CS1591
        [EnumMember(Value = "selfie.submitted")]
        #pragma warning disable CS1591
        SelfieSubmitted,
        #pragma warning restore CS1591
        [EnumMember(Value = "selfie.processed")]
        #pragma warning disable CS1591
        SelfieProcessed,
        #pragma warning restore CS1591
        [EnumMember(Value = "selfie.errored")]
        #pragma warning disable CS1591
        SelfieErrored,
        #pragma warning restore CS1591
        [EnumMember(Value = "transaction.created")]
        #pragma warning disable CS1591
        TransactionCreated,
        #pragma warning restore CS1591
        [EnumMember(Value = "transaction.labeled")]
        #pragma warning disable CS1591
        TransactionLabeled,
        #pragma warning restore CS1591
        [EnumMember(Value = "transaction.redacted")]
        #pragma warning disable CS1591
        TransactionRedacted,
        #pragma warning restore CS1591
        [EnumMember(Value = "transaction.status-updated")]
        #pragma warning disable CS1591
        TransactionStatusUpdated,
        #pragma warning restore CS1591
        [EnumMember(Value = "verification.created")]
        #pragma warning disable CS1591
        VerificationCreated,
        #pragma warning restore CS1591
        [EnumMember(Value = "verification.submitted")]
        #pragma warning disable CS1591
        VerificationSubmitted,
        #pragma warning restore CS1591
        [EnumMember(Value = "verification.passed")]
        #pragma warning disable CS1591
        VerificationPassed,
        #pragma warning restore CS1591
        [EnumMember(Value = "verification.failed")]
        #pragma warning disable CS1591
        VerificationFailed,
        #pragma warning restore CS1591
        [EnumMember(Value = "verification.requires-retry")]
        #pragma warning disable CS1591
        VerificationRequiresRetry,
        #pragma warning restore CS1591
        [EnumMember(Value = "verification.canceled")]
        #pragma warning disable CS1591
        VerificationCanceled,
        #pragma warning restore CS1591
    }
}
