// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Persona.OpenApiClient.Models
{
    /// <summary>Default key inflection for attribute keys in incoming webhook requests. For more info see the [Key Inflection docs](https://docs.withpersona.com/key-inflection).</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum WebhookRequestAttributes_apiKeyInflection
    {
        [EnumMember(Value = "camel")]
        #pragma warning disable CS1591
        Camel,
        #pragma warning restore CS1591
        [EnumMember(Value = "kebab")]
        #pragma warning disable CS1591
        Kebab,
        #pragma warning restore CS1591
        [EnumMember(Value = "snake")]
        #pragma warning disable CS1591
        Snake,
        #pragma warning restore CS1591
    }
}
