// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Persona.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Workflow_1_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "workflow")]
        #pragma warning disable CS1591
        Workflow,
        #pragma warning restore CS1591
    }
}
