// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Persona.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Persona.OpenApiClient.InquirySessions.ExpireAll
{
    /// <summary>
    /// Builds and executes requests for operations under \inquiry-sessions\expire-all
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ExpireAllRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Persona.OpenApiClient.InquirySessions.ExpireAll.ExpireAllRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ExpireAllRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/inquiry-sessions/expire-all{?fields*,include*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Persona.OpenApiClient.InquirySessions.ExpireAll.ExpireAllRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ExpireAllRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/inquiry-sessions/expire-all{?fields*,include*}", rawUrl)
        {
        }
        /// <summary>
        /// Expires all active Inquiry Sessions for a given set of Inquiries.
        /// Full documentation for this API on the Persona website. <see href="https://docs.withpersona.com/api-reference/inquiry-sessions/expire-inquiry-sessions" />
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Persona.OpenApiClient.Models.ExpireInquirySessions200"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Persona.OpenApiClient.Models.ExpireInquirySessions200400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Persona.OpenApiClient.Models.ExpireInquirySessions200401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Persona.OpenApiClient.Models.ExpireInquirySessions200403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Persona.OpenApiClient.Models.ExpireInquirySessions200409Error">When receiving a 409 status code</exception>
        /// <exception cref="global::Soenneker.Persona.OpenApiClient.Models.ExpireInquirySessions200422Error">When receiving a 422 status code</exception>
        /// <exception cref="global::Soenneker.Persona.OpenApiClient.Models.ExpireInquirySessions200429Error">When receiving a 429 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Persona.OpenApiClient.Models.ExpireInquirySessions200?> PostAsync(global::Soenneker.Persona.OpenApiClient.Models.ExpireInquirySessions body, Action<RequestConfiguration<global::Soenneker.Persona.OpenApiClient.InquirySessions.ExpireAll.ExpireAllRequestBuilder.ExpireAllRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Persona.OpenApiClient.Models.ExpireInquirySessions200> PostAsync(global::Soenneker.Persona.OpenApiClient.Models.ExpireInquirySessions body, Action<RequestConfiguration<global::Soenneker.Persona.OpenApiClient.InquirySessions.ExpireAll.ExpireAllRequestBuilder.ExpireAllRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Persona.OpenApiClient.Models.ExpireInquirySessions200400Error.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Persona.OpenApiClient.Models.ExpireInquirySessions200401Error.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Persona.OpenApiClient.Models.ExpireInquirySessions200403Error.CreateFromDiscriminatorValue },
                { "409", global::Soenneker.Persona.OpenApiClient.Models.ExpireInquirySessions200409Error.CreateFromDiscriminatorValue },
                { "422", global::Soenneker.Persona.OpenApiClient.Models.ExpireInquirySessions200422Error.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Persona.OpenApiClient.Models.ExpireInquirySessions200429Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Persona.OpenApiClient.Models.ExpireInquirySessions200>(requestInfo, global::Soenneker.Persona.OpenApiClient.Models.ExpireInquirySessions200.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Expires all active Inquiry Sessions for a given set of Inquiries.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Persona.OpenApiClient.Models.ExpireInquirySessions body, Action<RequestConfiguration<global::Soenneker.Persona.OpenApiClient.InquirySessions.ExpireAll.ExpireAllRequestBuilder.ExpireAllRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Persona.OpenApiClient.Models.ExpireInquirySessions body, Action<RequestConfiguration<global::Soenneker.Persona.OpenApiClient.InquirySessions.ExpireAll.ExpireAllRequestBuilder.ExpireAllRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Persona.OpenApiClient.InquirySessions.ExpireAll.ExpireAllRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Persona.OpenApiClient.InquirySessions.ExpireAll.ExpireAllRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Persona.OpenApiClient.InquirySessions.ExpireAll.ExpireAllRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Expires all active Inquiry Sessions for a given set of Inquiries.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ExpireAllRequestBuilderPostQueryParameters 
        {
            /// <summary>Comma-separated list(s) of attributes to include in the response. This can be used to customize which attributes will be serialized in the response. See [Serialization](https://docs.withpersona.com/serialization#sparse-fieldsets) for more details.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("fields")]
            public string? Fields { get; set; }
#nullable restore
#else
            [QueryParameter("fields")]
            public string Fields { get; set; }
#endif
            /// <summary>A comma-separated list of relationship paths. This can be used to customize which related resources will be fully serialized in the `included` key in the response. See [Serialization](https://docs.withpersona.com/serialization#inclusion-of-related-resources) for more details.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("include")]
            public string? Include { get; set; }
#nullable restore
#else
            [QueryParameter("include")]
            public string Include { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
